/*
 * ***** BEGIN LICENSE BLOCK *****
 * Version: MPL 1.1
 * 
 * The contents of this file are subject to the Mozilla Public License
 * Version 1.1 ("License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.zimbra.com/license
 * 
 * Software distributed under the License is distributed on an "AS IS"
 * basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
 * the License for the specific language governing rights and limitations
 * under the License.
 * 
 * The Original Code is: Zimbra Collaboration Suite Server.
 * 
 * The Initial Developer of the Original Code is Zimbra, Inc.
 * Portions created by Zimbra are Copyright (C) 2005, 2006 Zimbra, Inc.
 * All Rights Reserved.
 * 
 * Contributor(s): 
 * 
 * ***** END LICENSE BLOCK *****
 */
 
package com.zimbra.cs.im.xp.parse;

/**
 * The keys of the messages that can be generated by <code>EntityParser</code>.
 * @see EntityParser
 * @version $Revision: 1.6 $ $Date: 1998/05/14 02:04:05 $
 */

interface MessageId {
  /* Using the same name of the identifier as the string saves space
     in the class file. */
  static final String MESSAGE_FORMAT = "MESSAGE_FORMAT";
  static final String PUBID_CHAR = "PUBID_CHAR";
  static final String ELEMENT_AFTER_DOCUMENT_ELEMENT = "ELEMENT_AFTER_DOCUMENT_ELEMENT";
  static final String BAD_INITIAL_BYTES = "BAD_INITIAL_BYTES";
  static final String BAD_DECL_ENCODING = "BAD_DECL_ENCODING";
  static final String INVALID_XML_DECLARATION = "INVALID_XML_DECLARATION";
  static final String IGNORE_SECT_CHAR = "IGNORE_SECT_CHAR";
  static final String INVALID_END_TAG = "INVALID_END_TAG";
  static final String EPILOG_JUNK = "EPILOG_JUNK";
  static final String MISMATCHED_END_TAG = "MISMATCHED_END_TAG";
  static final String MISPLACED_XML_DECL = "MISPLACED_XML_DECL";
  static final String MISSING_END_TAG = "MISSING_END_TAG";
  static final String NO_DOCUMENT_ELEMENT = "NO_DOCUMENT_ELEMENT";
  static final String NOT_WELL_FORMED = "NOT_WELL_FORMED";
  static final String PE_GROUP_NESTING = "PE_GROUP_NESTING";
  static final String PE_DECL_NESTING = "PE_DECL_NESTING";
  static final String INTERNAL_PEREF_ENTVAL = "INTERNAL_PEREF_ENTVAL";
  static final String RECURSION = "RECURSION";
  static final String EXTERN_REF_ATTVAL = "EXTERN_REF_ATTVAL";
  static final String UNDEF_REF = "UNDEF_REF";
  static final String UNDEF_PEREF = "UNDEF_PEREF";
  static final String UNPARSED_REF = "UNPARSED_REF";
  static final String SYNTAX_ERROR = "SYNTAX_ERROR";
  static final String UNCLOSED_CDATA_SECTION = "UNCLOSED_CDATA_SECTION";
  static final String UNCLOSED_CONDITIONAL_SECTION = "UNCLOSED_CONDITIONAL_SECTION";
  static final String UNCLOSED_TOKEN = "UNCLOSED_TOKEN";
  static final String UNSUPPORTED_ENCODING = "UNSUPPORTED_ENCODING";
  static final String DUPLICATE_ATTRIBUTE = "DUPLICATE_ATTRIBUTE";
  static final String XML_TARGET = "XML_TARGET";
  static final String ILLEGAL_CHAR = "ILLEGAL_CHAR";
}
