// ExchangeMigration.idl : IDL source for ExchangeMigration
//

// This file will be processed by the MIDL tool to
// produce the type library (ExchangeMigration.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(C5E4267C-AE6C-4E31-956A-06D8094D0CBE),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IMapiWrapper : IDispatch{
	[id(1), helpstring("This method can be used to connect to ZCO server")] HRESULT ConnectToServer(BSTR ServerHostName, BSTR Port, BSTR AdminID);
	[id(2), helpstring("Method to connect to Exchange server")] HRESULT ConnecttoXchgServer([in] BSTR HostName, BSTR ProfileName, BSTR Password);
	[id(3), helpstring("Method to import all the options, input is the tag name for options")] HRESULT ImportMailOptions([in] BSTR OptionsTag);
};
[
	uuid(33449EAA-8056-4D28-8D42-552B7C6C8954),
	version(1.0),
]
library ExchangeMigrationLib
{
	importlib("stdole2.tlb");
	[
		uuid(A6A12B55-AE1E-449D-A646-19E0DB020EA2)		
	]
	coclass MapiWrapper
	{
		[default] interface IMapiWrapper;
	};
};

