#!/bin/bash

# Example:
#
# 1. untar tzdata20xxx.tar.gz to tzdata subdir.
# 2. Run: zmtzdata2ical -o timezones.ics -e extra-data -t tzdata windows-names
# 3. Install generated timezones.ics under /opt/zimbra/conf.
# 4. Restart mailboxd.

exec zmjava com.zimbra.common.calendar.ZoneInfo2iCalendar "$@"
