AjxPackage.require("ajax.3rdparty.modernizr.modernizr");
AjxPackage.require("ajax.boot.AjxJson");
AjxPackage.require("ajax.boot.AjxEnv");
AjxPackage.require("ajax.boot.AjxCallback");
AjxPackage.require("ajax.boot.AjxLoader");
AjxPackage.require("ajax.boot.AjxPackage");
AjxPackage.require("ajax.boot.AjxTemplate");
AjxPackage.require("ajax.boot.AjxTemplateCompiler");
AjxPackage.require("ajax.boot.AjxDispatcher");
