#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# 
# Zimbra Collaboration Suite Server
# Copyright (C) 2010, 2011, 2012 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# 
# ***** END LICENSE BLOCK *****
# 

source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars zmconfigd_listen_port

NC=`which nc 2>/dev/null`; NC=${NC:-`which netcat 2>/dev/null`}

echo REWRITE $@ | $NC -w 120 localhost ${zmconfigd_listen_port} > /dev/null 2>&1
rc=$?

# If nc fails to connect, run zmconfigd directly
if [ $rc -ne 0 ]; then
	/opt/zimbra/libexec/zmconfigd $@
	rc=$?
	stty echo
else
	sleep 5
fi
exit $rc
