#!/usr/bin/perl
# 
# ***** BEGIN LICENSE BLOCK *****
# 
# Zimbra Collaboration Suite Server
# Copyright (C) 2006 Zimbra, Inc.
# 
# The contents of this file are subject to the Yahoo! Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# 
# ***** END LICENSE BLOCK *****
# 

sub handleTerm {
	print "SIGTERM received, exiting\n";
	`/opt/zimbra/bin/zmcontrol stop >> /opt/zimbra/log/zcs.log 2>&1`;
	exit 0;
}

$SIG{TERM} = \&handleTerm;

if ($ARGV[0] eq "start") {
	`/opt/zimbra/bin/zmcontrol start >> /opt/zimbra/log/zcs.log 2>&1`;
	sleep;
}
