#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.zimbra.com/license
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is: Zimbra Collaboration Suite Server.
# 
# The Initial Developer of the Original Code is Zimbra, Inc.
# Portions created by Zimbra are Copyright (C) 2006 Zimbra, Inc.
# All Rights Reserved.
# 
# Contributor(s):
# 
# ***** END LICENSE BLOCK *****
# 
#
# Init file for zimbra mail
#
# chkconfig: 345 99 01
# description: Zimbra mail service
#


command()
{
	if [ -f /opt/zimbra/redolog/redo.log ]; then
		chown -f zimbra:zimbra /opt/zimbra/redolog/redo.log
	fi
	su - zimbra -c "zmcontrol $1 </dev/null >>/opt/zimbra/log/startup.log 2>&1"
}

case "$1" in
	restart)
		command shutdown
		command startup
		RETVAL=$?
    if [ -d /var/lock/subsys -a $RETVAL -eq 0 ]; then
      touch /var/lock/subsys/zimbra
    fi
		;;
	start)
		command startup
		RETVAL=$?
    if [ -d /var/lock/subsys -a $RETVAL -eq 0 ]; then
      touch /var/lock/subsys/zimbra
    fi
		;;
	stop)
		command shutdown
		RETVAL=$?
    if [ -d /var/lock/subsys -a $RETVAL -eq 0 ]; then
      rm -f /var/lock/subsys/zimbra
    fi
		;;
	reload|status)
		command $1
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|reload|status}"
		RETVAL=1
esac
exit $RETVAL
