#!/usr/bin/perl
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2009, 2010, 2011 VMware, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
use strict;
use lib qw(/opt/zimbra/zimbramon/lib /opt/zimbra/libexec/scripts);
use Net::DNS;
use Socket;
use Net::LDAP;
use Getopt::Long;

my (%c,%loaded,%saved,$rc);
my ($help, $verbose, $force);

my (undef, undef,$uid,$gid) = getpwnam('zimbra');
if ($> ne $uid) {
  print "Must be run as user zimbra.\n";
  &usage
}

GetOptions("help" => \$help, 
    "force" => \$force,
    "verbose+" => \$verbose);

&usage if ($help);

$c{zmlocalconfig}="/opt/zimbra/bin/zmlocalconfig";
$c{zimbra_home} = getLocalConfig("zimbra_home");
$c{zmprov}="$c{zimbra_home}/bin/zmprov -l --";

# ***** Main *****
my $ldappass = `$c{zmlocalconfig} -s -m nokey zimbra_ldap_password`;
my $ldapdn  = `$c{zmlocalconfig} -s -m nokey zimbra_ldap_userdn`;
my $ldapurl  = `$c{zmlocalconfig} -s -m nokey ldap_url`;
chop($ldappass);
chop($ldapdn);
chop($ldapurl);

my $ldap = Net::LDAP->new( $ldapurl ) or die "Error connecting to LDAP server: $ldapurl";
my $mesg = $ldap->bind( $ldapdn, password => $ldappass );
$mesg->code && die "Error binding to LDAP server: $mesg->error";

my $ldapquery = "(objectClass=zimbraGlobalConfig)";
$mesg = $ldap->search(
                  base => '',
                  filter => $ldapquery,
                  attrs => [
                      'zimbraDomainMandatoryMailSignatureEnabled',
                      'zimbraDomainMandatoryMailSignatureText',
                      'zimbraDomainMandatoryMailSignatureHTML'
                  ]
              );
my $i = 0;
my $enabled = $mesg->entry($i)->get_value('zimbraDomainMandatoryMailSignatureEnabled');
print "Getting global config zimbraDomainMandatoryMailSignatureEnabled=$enabled\n";

if (lc($enabled) eq "true") {
  my $text = $mesg->entry($i)->get_value('zimbraDomainMandatoryMailSignatureText');
  my $html = $mesg->entry($i)->get_value('zimbraDomainMandatoryMailSignatureHTML');
  writeFile("$c{zimbra_home}/data/altermime/global-default.txt", "$text");
  writeFile("$c{zimbra_home}/data/altermime/global-default.html", "$html");
}

exit 0;
# ***** End Main *****


# ***** Subroutines *****
sub usage {
  print "\n";
  print "Usage: $0 [-h] [-f] [-v]\n";
  print " --help: print this usage statement.\n";
  print " --force: Force the rename, bypassing safety checks.\n";
  print " --verbose: Set the verbosity level.\n";
  print "\n";
  exit 0; 
}

sub writeFile($$) {
  my ($file, $content) = @_;
  open(DATA, ">$file");
  print DATA "$content";
  print DATA "\n";
  close(DATA);
}

sub getLocalConfig {
  my ($key,$force) = @_;

  return $loaded{lc}{$key}
    if (exists $loaded{lc}{$key} && !$force);
  print "Getting local config $key=";
  my $val = `$c{zmlocalconfig} -x -s -m nokey ${key} 2> /dev/null`;
  chomp $val;
  $loaded{lc}{$key} = $val;
  print "$val\n"; 
  return $val;
}

