#!/usr/bin/perl -w
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2012, 2013 Zimbra Software, LLC.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.4 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
use Getopt::Long;
use lib "/opt/zimbra/zimbramon/lib";
use IO::Compress::Gzip qw(gzip $GzipError);
sub scanLogDirectory;
sub getLocalConfigValue;
sub usage;

my ($help, $verbose);
GetOptions("help" => \$help,
           "verbose" => \$verbose);
      
my $zimbra_home=getLocalConfigValue("zimbra_home");
$zimbra_home = "/opt/zimbra" if ($zimbra_home eq "");
my $zimbra_log_directory="${zimbra_home}/log";

my @logfiles = qw(mailbox.log audit.log sync.log synctrace.log wbxml.log milter.log convertd.log);

usage() if $help;
scanLogDirectory($zimbra_log_directory);


sub usage() {
  print "$0 [-help] [-verbose]\n";
  exit;
}

sub scanLogDirectory($) {
  my ($logDirectory) = @_;
   if (opendir DIR, "$logDirectory") {
    my @logs = grep { !/^[\._]/ } readdir(DIR);
    foreach my $log (@logs) {
      next if ($log =~ /\.gz$/); # skip files already compressed.
      next if ($log !~ /\.\d{4}-\d{2}-\d{2}$/);
      foreach $str (@logfiles) {
        if ($log =~ /$str/) {
          compressLogFile("$logDirectory/$log");
        }
      }
    }
  }
}

sub compressLogFile($) {
  my ($logfile) = @_;
  if (gzip $logfile => "$logfile.gz") {
    print "Compressed $logfile.\n" if $verbose;
    unlink($logfile);
  } else {
    print "compression failed for $logfile. $GzipError\n";
  }
}

sub getLocalConfigValue($) {
  my ($key) = @_;
  my $val = qx(/opt/zimbra/bin/zmlocalconfig -x -s -m nokey ${key} 2> /dev/null);
  chomp $val;
  return $val;
}
