#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
#
# Zimbra Collaboration Suite Server
# Copyright (C) 2005-2012 VMware, Inc. VMware and Zimbra are registered trademarks of VMware, Inc.
# 
# ***** END LICENSE BLOCK *****
# 
source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars -f zimbra_home

while [ $# -gt 0 ]
do
    if [ "$1" == "-h" -o "$1" == "--help" ]
	then
	    echo "usage: $0 [ -h | --help ]"
		echo "Compute current total aggregate quota used by each domain in the system and update LDAP with the data."
		echo ""
		echo "  -h, --help    display this help and exit"
		echo ""
		exit 0
	else
		echo "Usage: $0 [ -h | --help ]"
		echo "Compute current total aggregate quota used by each domain in the system and update LDAP with the data."
		echo ""
		echo "  -h, --help    display this help and exit"
		echo ""
		exit 1
    fi
done

exec ${zimbra_home}/bin/zmjava com.zimbra.common.soap.SoapCommandUtil -z ComputeAggregateQuotaUsageRequest

