#!/usr/bin/perl
#
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2006, 2007, 2008, 2009, 2010 Zimbra, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****

=head1 NAME

zmdailyreport - report on email usage

=head1 SYNOPSIS

Usage: zmdailyreport [options]

  Options:
    --mail                 Send report via email, default is stdout
    --help                 This help message

=cut
#    --user <email_address> Report usage for <email_address> only
#    --time <start>,<end>   Default is midnight to midnight of the previous day
#    --now                  Shortcut for midnight to the current time
use warnings;
use strict;
use Pod::Usage qw(pod2usage);
use lib "/opt/zimbra/zimbramon/lib";
use Zimbra::Util::Common;
use Zimbra::Mon::Logger;
use Getopt::Long qw(GetOptions);
use Mail::Mailer ();
use POSIX qw(strftime setlocale LC_TIME);
use Time::Local qw(timelocal);

my ( %Opt, $Debug );

GetOptions( \%Opt, "mailreport", "now", "debug", "user=s", "time=s", "help" )
  or pod2usage( -exitval => 2 );
  
pod2usage( -exitval => 1, -verbose => 0 ) if ( $Opt{help} );

$Debug = $Opt{debug};

setlocale(LC_TIME, "C");
my $stdout;
open($stdout, ">&STDOUT") || die $!;
pipe(PFIN, PFOUT);
pipe(MIN, MOUT);
my $fhin = fileno(PFIN);
close(STDIN);
open(STDIN, "<&=$fhin") || die $!;


if (fork()) {
	close(MOUT);
	my $today = strftime("%b %e ", localtime);
	my $datestring = strftime("%F", localtime);
	my $ymd = strftime("%Y%m%d", localtime);
	
	my $found = 0;
	my $old_log;
	if (-f "/var/log/zimbra.log.1.gz") {
		$old_log = "gzip -dc /var/log/zimbra.log.1.gz |";
	} elsif (-f "/var/log/zimbra.log-$ymd.gz") {
		$old_log = "bzip2 -dc /var/log/zimbra.log-$ymd.gz |";
	} elsif (-f "/var/log/zimbra.log.1.bz2") {
		$old_log = "bzip2 -dc /var/log/zimbra.log.1.bz2 |";
	} elsif (-f "/var/log/zimbra.log-$ymd.bz2") {
		$old_log = "bzip2 -dc /var/log/zimbra.log-$ymd.bz2 |";
	}
	if (defined($old_log)) {
	    if (open(LOG, $old_log)) {
	    	
            while (<LOG>) {
		        my $line = $_;
		        if ($line =~ /$today/o) {
   		             print PFOUT $line;
   		             $found = 1;
	            } elsif ($found) {
	    	        last; # don't scan any further, we've exhausted today's logs
	            }
	        }
		    close(LOG);
	    }
		
	}
	open(LOG, "</var/log/zimbra.log") || die $!;
	$found = 0;
	while (<LOG>) {
		my $line = $_;
		if ($line =~ /$today/o) {
   		     print PFOUT $line;
   		     $found = 1;
	    } elsif ($found) {
	    	last; # don't scan any further, we've exhausted today's logs
	    }
	}
	close(LOG);
	close(PFOUT);
	
	my @Report;
	while (<MIN>) {
		push(@Report, $_);
	}
	close (MIN);
	
	if ($Opt{mailreport}) {
		sendEmailReport(day => $datestring, data => \@Report);
	} else {
		print @Report;
	}
} else {
	close(PFOUT);
	close(MIN);
	open(STDOUT, ">&MOUT") || die $!;
	my $user_limit = getLocalConfig('zimbra_mtareport_max_users') || 50;
	my $host_limit = getLocalConfig('zimbra_mtareport_max_hosts') || 50;
	$user_limit = 50 if $user_limit !~ /^\d+/;
	$host_limit = 50 if $host_limit !~ /^\d+/;
    @ARGV = ('-u', $user_limit, '-h', $host_limit);
    do '/opt/zimbra/libexec/pflogsumm.pl';
    close(STDOUT);
}

{    # avoid making $LocalConfig global
    my $LocalConfig;

    sub getLocalConfig {
        my $key = shift;
        $LocalConfig = loadLocalConfig() unless ($LocalConfig);
        return $LocalConfig->{$key};
    }
}

sub loadLocalConfig {
    my %conf;

    open( CONF, "/opt/zimbra/bin/zmlocalconfig -s -q -m shell |" )
      or die("Open local config failed: $!\n");

    while (<CONF>) {
        chomp;
        my ( $key, $val ) = split( /=/, $_, 2 );
        $val =~ s/';$//;
        $val =~ s/^'//;
        $conf{$key} = $val;
    }
    die("No data returned from local config") unless ( keys %conf );
    return \%conf;
}

sub getLdapConfigValue {
    my $attrib = shift;

    return (undef) unless ($attrib);

    my $val = getLdapServerConfigValue($attrib);
    print "Server: $val\n" if $Debug;
    $val = getLdapGlobalConfigValue($attrib) if ($val eq "");
    print "Global: $val\n" if $Debug;
    return $val;
}

sub getLdapServerConfigValue {
    my $attrib = shift;

    return (undef) unless ($attrib);
    my $server = getLocalConfig("zimbra_server_hostname");
    # could consider redirecting STDERR to /dev/null
    open( CONF, "/opt/zimbra/bin/zmprov -l gs $server '$attrib' |" )
      or die("Open global config failed: $!");

    my ( $key, $val );
    while (<CONF>) {
        chomp;
        next if (/^#/);
        ( $key, $val ) = split( /:\s*/, $_, 2 );
        # for now just assume a single value/attribute is requested
        last if ($val);
    }
    return $val;
}

sub getLdapGlobalConfigValue {
    my $attrib = shift;

    return (undef) unless ($attrib);

    # could consider redirecting STDERR to /dev/null
    open( CONF, "/opt/zimbra/bin/zmprov -l gcf '$attrib' |" )
      or die("Open global config failed: $!");

    my ( $key, $val );
    while (<CONF>) {
        chomp;
        ( $key, $val ) = split( /:\s*/, $_, 2 );

        # for now just assume a single value/attribute is requested
        last if ($val);
    }
    return $val;
}

sub sendEmailReport {
    my %arg = @_;

    my $data = $arg{data};    # @Report data for message body

    my $subject      = "Daily mail report for $arg{day}";
    my $from_address = getLocalConfig("smtp_source");
    my $to_address   = getLocalConfig("smtp_destination");
    my $smtphost     = getLdapConfigValue("zimbraSmtpHostname") || "localhost";

    warn("DEBUG: Sending daily report to $to_address via $smtphost\n")
      if ($Debug);

    eval {
        my $mailer = Mail::Mailer->new( "smtp", Server => $smtphost );
        $mailer->open(
            {
                From    => $from_address,
                To      => $to_address,
                Subject => $subject,
            }
        );
        print $mailer @$data;
        $mailer->close();
    };
    if ($@) {
        logError("Failed to email report using SMTP via '$smtphost': $@\n");
    }
    else {
        warn("DEBUG: Email report sent to $to_address\n") if ($Debug);
    }
}
