#!/bin/bash 
# 
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.zimbra.com/license
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is: Zimbra Collaboration Suite Server.
# 
# The Initial Developer of the Original Code is Zimbra, Inc.
# Portions created by Zimbra are Copyright (C) 2005, 2006 Zimbra, Inc.
# All Rights Reserved.
# 
# Contributor(s):
# 
# ***** END LICENSE BLOCK *****
# 
# This may not be there, but we don't want to break the zimbramta package
# if it's installed.

root_user=root
zimbra_home=/opt/zimbra

PLAT=`/bin/sh ${zimbra_home}/libexec/get_plat_tag.sh`
if [ "X$PLAT" = "XMACOSX" -o "X$PLAT" = "XMACOSXx86" ]; then
	root_group=wheel
else 
  root_group=root
fi

# NOT ${zimbra_home}/{store,backup,index}
chown -R zimbra:zimbra ${zimbra_home}/a* ${zimbra_home}/[c-hj-ot-z]* ${zimbra_home}/s[a-su-z]*

chown ${root_user}:${root_group} ${zimbra_home}
chmod 755 ${zimbra_home}
chown -R ${root_user}:${root_group} ${zimbra_home}/libexec
chmod 755 ${zimbra_home}/libexec/*
chown -R ${root_user}:${root_group} ${zimbra_home}/bin
chmod 755 ${zimbra_home}/bin/*
chown -R ${root_user}:${root_group} ${zimbra_home}/lib

# fix the temp directory
if [ ! -d /tmp/zimbra ]; then
  mkdir -p /tmp/zimbra
fi
chown zimbra:zimbra /tmp/zimbra
chmod 755 /tmp/zimbra

if [ -d ${zimbra_home}/jdk1.6.0_02 ]; then
	chown -R ${root_user}:${root_group} ${zimbra_home}/jdk1.6.0_02
fi

if [ -L ${zimbra_home}/cyrus-sasl ]; then
	chown ${root_user}:zimbra ${zimbra_home}/cyrus-sasl-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/cyrus-sasl/*
  if [ ! -d ${zimbra_home}/cyrus-sasl/state ]; then  
    mkdir -p ${zimbra_home}/cyrus-sasl/state
  fi
  chown -R zimbra:zimbra ${zimbra_home}/cyrus-sasl/{etc,state}
  chmod 755 ${zimbra_home}/cyrus-sasl/state 
fi

if [ -L ${zimbra_home}/dspam ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/dspam-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/dspam/*
fi
chown  root:$ROOTGROUP /opt/zimbra/jetty-*

if [ -L ${zimbra_home}/httpd ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/httpd-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/httpd/*
fi

if [ -L ${zimbra_home}/logger/mysql ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/logger/mysql-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/logger/mysql/*
fi

if [ -L ${zimbra_home}/mysql ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/mysql-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/mysql/*
fi

if [ -L ${zimbra_home}/snmp ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/net-snmp-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/snmp/*
fi

if [ -L ${zimbra_home}/openldap ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/openldap-*
  chown -R zimbra:zimbra ${zimbra_home}/openldap-data
  chown -R ${root_user}:${root_group} ${zimbra_home}/openldap/*
  chown -R zimbra:zimbra ${zimbra_home}/openldap/{etc,var}
	chmod 755 ${zimbra_home}/openldap/libexec/*
fi

if [ -L ${zimbra_home}/perdition ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/perdition-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/perdition/*
fi

if [ -L ${zimbra_home}/sleepycat ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/sleepycat-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/sleepycat/*
fi

if [ -L ${zimbra_home}/clamav ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/clamav-*
	chown ${root_user}:${root_group} ${zimbra_home}/clamav/*
  chown -R zimbra:zimbra ${zimbra_home}/clamav/db
fi

if [ -L ${zimbra_home}/amavisd ]; then
	chown ${root_user}:${root_group} ${zimbra_home}/amavisd/sbin
fi

if [ -L ${zimbra_home}/aspell ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/aspell-*
	chown ${root_user}:${root_group} ${zimbra_home}/aspell/*
fi

if [ -L ${zimbra_home}/tomcat ]; then
  chown -R zimbra:zimbra ${zimbra_home}/apache-tomcat-*
  chown  ${root_user}:${root_group} ${zimbra_home}/apache-tomcat-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/tomcat/bin
  if [ ! -d ${zimbra_home}/tomcat/conf ]; then
	  mkdir -p ${zimbra_home}/tomcat/conf
	  chown zimbra:zimbra ${zimbra_home}/tomcat/conf
  fi
fi

if [ -d ${zimbra_home}/zimbramon/lib ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/zimbramon
  chown -R ${root_user}:${root_group} ${zimbra_home}/zimbramon/lib
fi

if [ -L ${zimbra_home}/zimbramon/rrdtool ]; then
  chown ${root_user}:${root_group} ${zimbra_home}/zimbramon/rrdtool*
  chown -R ${root_user}:${root_group} ${zimbra_home}/zimbramon/rrdtool/*
fi

if [ -L ${zimbra_home}/postfix ]; then

	if [ ! -d ${zimbra_home}/postfix/spool ]; then
		mkdir -p ${zimbra_home}/postfix/spool
	fi
	chown -fR ${root_user}:${root_group} ${zimbra_home}/postfix*
	chown -fR postfix:postfix ${zimbra_home}/postfix/spool
	chown -fR ${root_user}:postfix ${zimbra_home}/postfix/conf
	chown -f root ${zimbra_home}/postfix/spool

	chmod 777 ${zimbra_home}/postfix/conf
	chmod -fR 644 ${zimbra_home}/postfix/conf/*
	chmod -f 755 ${zimbra_home}/postfix/conf/postfix-script
	chmod -f 755 ${zimbra_home}/postfix/conf/post-install

	# Postfix specific permissions
	if [ -d ${zimbra_home}/postfix/spool/public ]; then
		chgrp -f postdrop ${zimbra_home}/postfix/spool/public
	fi
	if [ -d ${zimbra_home}/postfix/spool/maildrop ]; then
		chmod 730 ${zimbra_home}/postfix/spool/maildrop
		chgrp -f postdrop ${zimbra_home}/postfix/spool/maildrop
		chmod 730 ${zimbra_home}/postfix/spool/maildrop
	fi
	if [ -d ${zimbra_home}/postfix/sbin ]; then
		chgrp -f postdrop ${zimbra_home}/postfix/sbin/postqueue
		chgrp -f postdrop ${zimbra_home}/postfix/sbin/postdrop
		chmod -f g+s ${zimbra_home}/postfix/sbin/postqueue
		chmod -f g+s ${zimbra_home}/postfix/sbin/postdrop
	fi

fi

if [ -f ${zimbra_home}/libexec/ZmSetup.app/Contents/MacOS/ZmSetup ]; then
	chown ${root_user}:${root_group} ${zimbra_home}/libexec/ZmSetup.app/Contents/MacOS/ZmSetup
	chmod 544 ${zimbra_home}/libexec/ZmSetup.app/Contents/MacOS/ZmSetup
fi

