#!/bin/bash 
# 
# ***** BEGIN LICENSE BLOCK *****
# 
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007 Zimbra, Inc.
# 
# The contents of this file are subject to the Yahoo! Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# 
# ***** END LICENSE BLOCK *****
# 
# This may not be there, but we don't want to break the zimbramta package
# if it's installed.
shopt -s nullglob

root_user=root
zimbra_home=/opt/zimbra

PLAT=`/bin/sh ${zimbra_home}/libexec/get_plat_tag.sh`
if [ "X$PLAT" = "XMACOSX" -o "X$PLAT" = "XMACOSXx86" ]; then
	root_group=wheel
else 
  root_group=root
fi

zimbra_user=zimbra
zimbra_group=zimbra

extended=no
verbose=no

usage() {
  echo "$0 [-help] [-extended] [-verbose]"
  echo "-help     Usage"
  echo "-verbose  Verbose output"
  echo "-extended Extended fix, includes store,index,backup directories"
  echo "          * Using extended option can take a signifcant amount of time."
  echo 
  exit
}

for opt in "$@"; do
  case "$opt" in
    -verbose|--verbose|-v)
      verbose=yes
      shift
      ;;
    -help|--help|-h|--h)
      usage
      shift
      ;;
    -extended|--extended|-e)
      extended=yes 
      shift
      ;;
    *)
      echo "Unknown option $opt"
      usage
      shift
      ;;
  esac
done

printMsg() {
  if [ $verbose = "yes" ]; then
    echo $*
  fi
}

# NOT ${zimbra_home}/{store,backup,index}
chown -R ${zimbra_user}:${zimbra_group} ${zimbra_home}/a* ${zimbra_home}/[c-hj-ot-z]* ${zimbra_home}/s[a-su-z]* 2> /dev/null

chown -R ${zimbra_user}:${zimbra_group} ${zimbra_home}/.viminfo ${zimbra_home}/.ldaprc ${zimbra_home}/.bash* ${zimbra_home}/.exrc 2> /dev/null

chown ${root_user}:${root_group} ${zimbra_home}
chmod 755 ${zimbra_home}
chown -R ${root_user}:${root_group} ${zimbra_home}/libexec
chmod 755 ${zimbra_home}/libexec/*
chown -R ${root_user}:${root_group} ${zimbra_home}/bin
chmod 755 ${zimbra_home}/bin/*
chown -R ${root_user}:${root_group} ${zimbra_home}/lib

# fix the temp directory
if [ ! -d /tmp/zimbra ]; then
  mkdir -p /tmp/zimbra
fi
chown ${zimbra_user}:${zimbra_group} /tmp/zimbra
chmod 755 /tmp/zimbra

if [ -f ${zimbra_home}/.install_history ]; then
  chmod 644 ${zimbra_home}/.install_history
fi

if [ -d ${zimbra_home}/jdk1.6.0_04 ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/java"
	chown -R ${root_user}:${root_group} ${zimbra_home}/jdk1.6.0_04
fi

if [ -d ${zimbra_home}/lib ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/lib"
  for i in ${zimbra_home}/lib/lib*so*; do
    chown ${root_user}:${root_group} $i
    chmod 755 $i
  done
  if [ -d ${zimbra_home}/lib/jars ]; then
    for i in ${zimbra_home}/lib/jars/*; do
      chown ${root_user}:${root_group} $i
      chmod 444 $i
    done
  fi
 
  if [ -d ${zimbra_home}/lib/ext ]; then
    find ${zimbra_home}/lib/ext -type f -exec chown ${root_user}:${root_group} {} \;
    find ${zimbra_home}/lib/ext -type f -exec chmod 444 {} \;
  fi
  if [ -d ${zimbra_home}/lib/ext-common ]; then
    find ${zimbra_home}/lib/ext-common -type f -exec chown ${root_user}:${root_group} {} \;
    find ${zimbra_home}/lib/ext-common -type f -exec chmod 444 {} \;
  fi
fi
   
if [ -d ${zimbra_home}/db ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/db"
  chown ${zimbra_user}:${zimbra_group} ${zimbra_home}/db/*.sql ${zimbra_home}/db/*.sql.in
  chmod 444 ${zimbra_home}/db/*.sql ${zimbra_home}/db/*.sql.in
fi

if [ -L ${zimbra_home}/cyrus-sasl ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/cyrus-sasl"
	chown ${root_user}:${zimbra_group} ${zimbra_home}/cyrus-sasl-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/cyrus-sasl/*
  if [ ! -d ${zimbra_home}/cyrus-sasl/state ]; then  
    mkdir -p ${zimbra_home}/cyrus-sasl/state
  fi
  chown -R ${zimbra_user}:${zimbra_group} ${zimbra_home}/cyrus-sasl/{etc,state}
  chmod 755 ${zimbra_home}/cyrus-sasl/state 
fi

if [ -L ${zimbra_home}/dspam ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/dspam"
  chown ${root_user}:${root_group} ${zimbra_home}/dspam-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/dspam/*
fi

if [ -L ${zimbra_home}/jetty ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/jetty"
  chown  ${root_user}:${root_group} /opt/zimbra/jetty-*
  if [ -f ${zimbra_home}/jetty/etc/keystore ]; then
    chmod 444 ${zimbra_home}/jetty/etc/keystore
    chown ${zimbra_user}:${zimbra_group} ${zimbra_home}/jetty/etc/keystore
  fi
  if [ -f ${zimbra_home}/jetty/webapps/zimbraAdmin/tmp/current.csr ]; then
    chown ${zimbra_user}:${zimbra_group} ${zimbra_home}/jetty/webapps/zimbraAdmin/tmp/current.csr
    chmod 444 ${zimbra_home}/jetty/webapps/zimbraAdmin/tmp/current.csr
  fi

  if [ ! -d ${zimbra_home}/fbqueue ]; then
    mkdir -p ${zimbra_home}/fbqueue
  fi
  chown ${zimbra_user}:${zimbra_group} ${zimbra_home}/fbqueue
  chmod 755 ${zimbra_home}/fbqueue

fi

if [ -d ${zimbra_home}/ssl ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/ssl"
  find ${zimbra_home}/ssl -type f -exec chown ${root_user}:${root_group} {} \;
  find ${zimbra_home}/ssl -type f -exec chmod 640 {} \;
fi

if [ -L ${zimbra_home}/httpd ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/httpd"
  chown ${root_user}:${root_group} ${zimbra_home}/httpd-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/httpd/*
fi

if [ -L ${zimbra_home}/logger/mysql ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/logger/mysql"
  chown ${root_user}:${root_group} ${zimbra_home}/logger/mysql-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/logger/mysql/*
fi

if [ -d ${zimbra_home}/logger/db ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/logger/db"
  chown ${zimbra_user}:${zimbra_group} ${zimbra_home}/logger/db
fi

if [ -L ${zimbra_home}/mysql ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/mysql"
  chown ${root_user}:${root_group} ${zimbra_home}/mysql-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/mysql/*
fi

if [ -L ${zimbra_home}/snmp ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/snmp"
  chown ${root_user}:${root_group} ${zimbra_home}/net-snmp-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/snmp/*
fi

if [ -L ${zimbra_home}/openldap ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/openldap"
  chown ${root_user}:${root_group} ${zimbra_home}/openldap-*
  chown -R ${zimbra_user}:${zimbra_group} ${zimbra_home}/openldap-data
  chown -R ${root_user}:${root_group} ${zimbra_home}/openldap/*
  chown -R ${zimbra_user}:${zimbra_group} ${zimbra_home}/openldap/{etc,var}
	chmod 755 ${zimbra_home}/openldap/libexec/*
fi

if [ -L ${zimbra_home}/perdition ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/perdition"
  chown ${root_user}:${root_group} ${zimbra_home}/perdition-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/perdition/*
fi

if [ -L ${zimbra_home}/sleepycat ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/sleepycat"
  chown ${root_user}:${root_group} ${zimbra_home}/sleepycat-*
  chown -R ${root_user}:${root_group} ${zimbra_home}/sleepycat/*
fi

if [ -L ${zimbra_home}/clamav ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/clamav"
  chown ${root_user}:${root_group} ${zimbra_home}/clamav-*
	chown ${root_user}:${root_group} ${zimbra_home}/clamav/*
  chown -R ${zimbra_user}:${zimbra_group} ${zimbra_home}/clamav/db
fi

if [ -L ${zimbra_home}/amavisd ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/amavisd"
	chown ${root_user}:${root_group} ${zimbra_home}/amavisd/sbin
fi

if [ -L ${zimbra_home}/aspell ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/aspell"
  chown ${root_user}:${root_group} ${zimbra_home}/aspell-*
	chown ${root_user}:${root_group} ${zimbra_home}/aspell/*
fi

if [ -L ${zimbra_home}/tomcat ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/tomcat"
  chown -R ${zimbra_user}:${zimbra_group} ${zimbra_home}/apache-tomcat-*
  chown  ${root_user}:${root_group} ${zimbra_home}/apache-tomcat-*
  if [ -d ${zimbra_home}/tomcat/bin ]; then
    chown -R ${root_user}:${root_group} ${zimbra_home}/tomcat/bin
    if [ ! -d ${zimbra_home}/tomcat/conf ]; then
	    mkdir -p ${zimbra_home}/tomcat/conf
	    chown ${zimbra_user}:${zimbra_group} ${zimbra_home}/tomcat/conf
    fi
  fi
fi

if [ -d ${zimbra_home}/zimbramon/lib ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/zimbramon/lib"
  chown ${root_user}:${root_group} ${zimbra_home}/zimbramon
  chown -R ${root_user}:${root_group} ${zimbra_home}/zimbramon/lib
fi

if [ -L ${zimbra_home}/zimbramon/rrdtool ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/rrdtool"
  chown ${root_user}:${root_group} ${zimbra_home}/zimbramon/rrdtool*
  chown -R ${root_user}:${root_group} ${zimbra_home}/zimbramon/rrdtool/*
fi

if [ -f ${zimbra_home}/conf/ZCSLicense.xml ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/conf/ZCSLicense.xml"
  chown ${root_user}:${root_group} ${zimbra_home}/conf/ZCSLicense.xml
  chmod 440 ${zimbra_home}/conf/ZCSLicense.xml
fi

if [ -L ${zimbra_home}/postfix ]; then
  printMsg "Fixing ownership and permisions on ${zimbra_home}/postfix"
	if [ ! -d ${zimbra_home}/postfix/spool ]; then
		mkdir -p ${zimbra_home}/postfix/spool
	fi
	chown -fR ${root_user}:${root_group} ${zimbra_home}/postfix*
	chown -fR postfix:postfix ${zimbra_home}/postfix/spool
	chown -fR ${root_user}:postfix ${zimbra_home}/postfix/conf
	chown -f root ${zimbra_home}/postfix/spool

	chmod 777 ${zimbra_home}/postfix/conf
	chmod -fR 644 ${zimbra_home}/postfix/conf/*
	chmod -f 755 ${zimbra_home}/postfix/conf/postfix-script
	chmod -f 755 ${zimbra_home}/postfix/conf/post-install

	# Postfix specific permissions
	if [ -d ${zimbra_home}/postfix/spool/public ]; then
		chgrp -f postdrop ${zimbra_home}/postfix/spool/public
	fi
	if [ -d ${zimbra_home}/postfix/spool/maildrop ]; then
		chmod 730 ${zimbra_home}/postfix/spool/maildrop
		chgrp -f postdrop ${zimbra_home}/postfix/spool/maildrop
		chmod 730 ${zimbra_home}/postfix/spool/maildrop
	fi
	if [ -d ${zimbra_home}/postfix/sbin ]; then
		chgrp -f postdrop ${zimbra_home}/postfix/sbin/postqueue
		chgrp -f postdrop ${zimbra_home}/postfix/sbin/postdrop
		chmod -f g+s ${zimbra_home}/postfix/sbin/postqueue
		chmod -f g+s ${zimbra_home}/postfix/sbin/postdrop
	fi

fi

if [ -d ${zimbra_home}/index -a ${extended} = "yes" ]; then
  printMsg "Fixing ownership of ${zimbra_home}/index"
  chown -R ${zimbra_user}:${zimbra_group} ${zimbra_home}/index
fi

if [ -d ${zimbra_home}/backup -a ${extended} = "yes" ]; then
  printMsg "Fixing ownership of ${zimbra_home}/backup"
  chown -R ${zimbra_user}:${zimbra_group} ${zimbra_home}/backup
fi

if [ -d ${zimbra_home}/store -a ${extended} = "yes" ]; then
  printMsg "Fixing ownership of ${zimbra_home}/store"
  chown -R ${zimbra_user}:${zimbra_group} ${zimbra_home}/store
fi

if [ -f ${zimbra_home}/libexec/ZmSetup.app/Contents/MacOS/ZmSetup ]; then
	chown ${root_user}:${root_group} ${zimbra_home}/libexec/ZmSetup.app/Contents/MacOS/ZmSetup
	chmod 544 ${zimbra_home}/libexec/ZmSetup.app/Contents/MacOS/ZmSetup
fi

exit 0

