#!/usr/bin/perl
#
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2008, 2009, 2010 Zimbra, Inc.
#
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
#
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
#
use strict;
use lib '/opt/zimbra/zimbramon/lib';
use Net::LDAP;
use Net::DNS::Resolver;
use Getopt::Long;

our %loaded = ();

my $id = getpwuid($<);
chomp $id;
if ($id ne "zimbra") {
    print STDERR "Error: must be run as zimbra user\n";
    exit (1);
}

my ($help, $dryrun, $mode);

my $opts_good = GetOptions(
  'h|help' => \$help,
  'd|dryrun' => \$dryrun,
  'm|mode=s' => \$mode,
);

if (!$opts_good) {
  print STDERR "\n";
  usage();
}

if ($help) {
  usage(0);
}

if ($mode && !$dryrun) {
  usage(0);
}

if ($mode && $mode ne "ipv4" && $mode ne "both" && $mode ne "ipv6") {
  usage(0);
}

my $ldapurl = getLocalConfig("ldap_url");
my $zdn = getLocalConfig("zimbra_ldap_userdn");
my $zps = getLocalConfig("zimbra_ldap_password");
my $ldap_starttls_supported = getLocalConfig("ldap_starttls_supported");
my $zimbra_home = getLocalConfig("zimbra_home");
my $host = getLocalConfig("zimbra_server_hostname");

if ($zimbra_home eq "") {
  $zimbra_home = "/opt/zimbra";
}

my $zmlocalconfig="${zimbra_home}/bin/zmlocalconfig";

my @replicas=split(/ /, $ldapurl);
my $replica_ref=\@replicas;
my $ldap = Net::LDAP->new( $replica_ref ) or die "Error connecting to LDAP server: $ldapurl";

my $mesg;
if ($ldapurl !~ /^ldaps/i) {
  if ($ldap_starttls_supported) {
    $mesg = $ldap->start_tls(
         verify => 'none',
         capath => "${zimbra_home}/conf/ca",
         ) or die "start_tls: $@";
    $mesg->code && die "TLS: " . $mesg->error . "\n";
  }
}

my $mesg = $ldap->bind("$zdn", password=>"$zps");
$mesg->code && die "Bind: ". $mesg->error . "\n";

my $zimbraIPMode;
my $size;
if ($mode) {
  $zimbraIPMode=$mode;
} else {
  $mesg = $ldap->search(
            base=>"",
            filter=>"(&(objectClass=zimbraServer)(cn=$host))",
            scope=>"sub",
            attrs => ['zimbraIPMode'],
          );
  
  $size = $mesg->count;
  if ($size == 0) {
    print "Error: Server $host not found\n";
    exit 1;
  }
  
  my $entry=$mesg->entry(0);
  $zimbraIPMode = $entry->get_value("zimbraIPMode");
}

$mesg = $ldap->search(
          base=>"",
          filter=>"(&(objectClass=zimbraServer)(cn=$host)(zimbraServiceEnabled=mailbox))",
          scope=>"sub",
        );

$size = $mesg->count;
my $storeserver=0;
if ($size > 0) {
  $storeserver=1;
}

my $mailboxd_java_options = getLocalConfig("mailboxd_java_options");
my $zimbra_zmjava_options = getLocalConfig("zimbra_zmjava_options");

if ($zimbraIPMode eq "ipv4") {
  my $ans = getDnsRecords($host, 'A');
  if (!defined($ans)) {
    print "Error: Unable to resolve $host A record\n";
  }
  if ($zimbra_zmjava_options !~ /-Djava.net.preferIPv4Stack=true/) {
      $zimbra_zmjava_options .= " -Djava.net.preferIPv4Stack=true";
  }
  if ($zimbra_zmjava_options =~ /-Djava.net.preferIPv6Addresses=true/) {
      $zimbra_zmjava_options =~ s/ -Djava.net.preferIPv6Addresses=true//;
  }
  if ($dryrun) {
    print "Would set zimbra_zmjava_options to $zimbra_zmjava_options\n";
  } else {
    setLocalConfig("zimbra_zmjava_options", $zimbra_zmjava_options);
  }
  if ($storeserver) {
    if ($mailboxd_java_options !~ /-Djava.net.preferIPv4Stack=true/) {
      $mailboxd_java_options .= " -Djava.net.preferIPv4Stack=true";
    }
    if ($mailboxd_java_options =~ /-Djava.net.preferIPv6Addresses=true/) {
      $mailboxd_java_options =~ s/ -Djava.net.preferIPv6Addresses=true//;
    }
    if ($dryrun) {
      print "Would set mailboxd_java_options to $mailboxd_java_options\n";
    } else {
      setLocalConfig("mailboxd_java_options", $mailboxd_java_options);
    }
  }
}
elsif ($zimbraIPMode eq "both") {
  my $ans = getDnsRecords($host, 'A');
  if (!defined($ans)) {
    print "Error: Unable to resolve $host A record\n";
  }
  my $ans = getDnsRecords($host, 'AAAA');
  if (!defined($ans)) {
    print "Error: Unable to resolve $host AAAA record\n";
  }
  if ($zimbra_zmjava_options =~ /-Djava.net.preferIPv4Stack=true/) {
    $zimbra_zmjava_options =~ s/ -Djava.net.preferIPv4Stack=true//;
  }
  if ($zimbra_zmjava_options =~ /-Djava.net.preferIPv6Addresses=true/) {
    $zimbra_zmjava_options =~ s/ -Djava.net.preferIPv6Addresses=true//;
  }
  if ($dryrun) {
    print "Would set zimbra_zmjava_options to $zimbra_zmjava_options\n";
  } else {
    setLocalConfig("zimbra_zmjava_options", $zimbra_zmjava_options);
  }
  if ($storeserver) {
    if ($mailboxd_java_options =~ /-Djava.net.preferIPv4Stack=true/) {
      $mailboxd_java_options =~ s/ -Djava.net.preferIPv4Stack=true//;
    }
    if ($mailboxd_java_options =~ /-Djava.net.preferIPv6Addresses=true/) {
      $mailboxd_java_options =~ s/ -Djava.net.preferIPv6Addresses=true//;
    }
    if ($dryrun) {
      print "Would set mailboxd_java_options to $mailboxd_java_options\n";
    } else {
      setLocalConfig("mailboxd_java_options", $mailboxd_java_options);
    }
  }
}
elsif ($zimbraIPMode eq "ipv6") {
  my $ans = getDnsRecords($host, 'AAAA');
  if (!defined($ans)) {
    print "Error: Unable to resolve $host AAAA record\n";
  }
  if ($zimbra_zmjava_options =~ /-Djava.net.preferIPv4Stack=true/) {
    $zimbra_zmjava_options =~ s/ -Djava.net.preferIPv4Stack=true//;
  }
  if ($zimbra_zmjava_options !~ /-Djava.net.preferIPv6Addresses=true/) {
    $zimbra_zmjava_options .= " -Djava.net.preferIPv6Addresses=true";
  }
  if ($dryrun) {
    print "Would set zimbra_zmjava_options to $zimbra_zmjava_options\n";
  } else {
    setLocalConfig("zimbra_zmjava_options", $zimbra_zmjava_options);
  }
  if ($storeserver) {
    if ($mailboxd_java_options =~ /-Djava.net.preferIPv4Stack=true/) {
      $mailboxd_java_options =~ s/ -Djava.net.preferIPv4Stack=true//;
    }
    if ($mailboxd_java_options !~ /-Djava.net.preferIPv6Addresses=true/) {
      $mailboxd_java_options .= " -Djava.net.preferIPv6Addresses=true";
    }
    if ($dryrun) {
      print "Would set mailboxd_java_options to $mailboxd_java_options\n";
    } else {
      setLocalConfig("mailboxd_java_options", $mailboxd_java_options);
    }
  }
}
else {
  print "Error: Unknown IP mode $zimbraIPMode\n";
  exit 1;
}

sub usage {
  my ($msg) = (@_);

  $msg && print STDERR "\nERROR: $msg\n";
  print STDERR <<USAGE;
  zmiptool [-d [-m ipmode]]

  Where:
  -d: dry run   Do not make any changes, just print what would be done.
  -m: IP Mode to test for if dryrun is enabled.  Optional

USAGE
        exit (1);

}
sub getLocalConfig {
  my $key = shift;

  return $main::loaded{lc}{$key}
    if (exists $main::loaded{lc}{$key});

  my $val = `/opt/zimbra/bin/zmlocalconfig -x -s -m nokey ${key} 2> /dev/null`;
  chomp $val;
  $main::loaded{lc}{$key} = $val;
  return $val;
}

sub setLocalConfig {
  my $key = shift;
  my $val = shift;
  print "Setting local config $key=$val\n";
  runCommand("$zmlocalconfig -f -e ${key}=\'${val}\' 2> /dev/null");
}

sub runCommand {
  my $cmd = shift;
  my $rc;
  $rc = 0xffff & system("$cmd > /dev/null 2>&1 ");
  return $rc;
}

sub getDnsRecords {
  my $name = shift;
  my $qtype = shift;

  my $res = Net::DNS::Resolver->new;
  my @servers = $res->nameservers();
  my $ans = $res->search ($name, $qtype);

  return $ans;
}
