#!/usr/bin/perl
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2008, 2009, 2010 Zimbra, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
use strict;
use lib '/opt/zimbra/zimbramon/lib';
use Net::LDAP;
use XML::Simple;
use Getopt::Long;
use File::Copy qw/ cp /;
use File::Path;

if ( ! -d "/opt/zimbra/openldap/etc" ) {
  print "ERROR: openldap does not appear to be installed - exiting\n";
  exit(1);
}

my $id = getpwuid($<);
chomp $id;
if ($id ne "zimbra") {
    print STDERR "Error: must be run as zimbra user\n";
    exit (1);
}
my ($help,$sid,$mmrURI,$rid);
$sid=0;
$rid=100;

my $opts_good = GetOptions(
        'h|help' => \$help,
        's|sid=i' => \$sid,
        'm|mmr=s' => \$mmrURI,
        'r|rid=i' => \$rid,
);

if (!$opts_good) {
        print STDERR "\n";
        usage();
}
if ($help) {
        usage(0);
}

if (!($mmrURI)) {
  usage(0);
}

if ($mmrURI !~ /^ldaps?:\/\//) {
  usage(0);
}

if ($mmrURI !~ /\/$/) {
  usage(0);
}

my $localxml = XMLin("/opt/zimbra/conf/localconfig.xml");
my $ldap_root_password = $localxml->{key}->{ldap_root_password}->{value};
chomp($ldap_root_password);
my $ldap_is_master = $localxml->{key}->{ldap_is_master}->{value};
chomp($ldap_is_master);
my $zimbra_home = $localxml->{key}->{zimbra_home}->{value};
my $ldap_replication_password = $localxml->{key}->{ldap_replication_password}->{value};
my $ldap_starttls_supported = $localxml->{key}->{ldap_starttls_supported}->{value};
my $zimbra_require_interprocess_security = $localxml->{key}->{zimbra_require_interprocess_security}->{value};

if ($zimbra_home eq "") {
   $zimbra_home = "/opt/zimbra";
}

if(lc($ldap_is_master) eq "true") {
  my $ldap = Net::LDAP->new('ldapi://%2fopt%2fzimbra%2fopenldap%2fvar%2frun%2fldapi/') or die "$@";
  my $mesg = $ldap->bind("cn=config", password=>"$ldap_root_password");
  $mesg->code && die "Bind: ". $mesg->error . "\n"; 

# Check to see if olcServerID is already configured.  If not, add it.

  my $dn="cn=config";
  $mesg = $ldap ->search(
                    base=>"$dn",
                    filter=>"(&(objectClass=olcGlobal)(olcServerID=*))",
                    scope=>"sub",
                    attrs => ['olcServerID'],
                );
  my $size = $mesg->count;
  if ($size == 0) {
    if($sid > 0) {
      $mesg = $ldap->modify(
        $dn,
        add=>{olcServerID =>"$sid"},
      );
    } else {
      print "Error: No Server ID exists on master and none provided.\n";
      print "       Provide valid Server ID value via the -s option.\n";
      exit(1);
    }
  }

  my $bdn="olcDatabase={2}mdb,cn=config";

#Check if master is already enabled for replication.  If so, steps are simpler.  If not, more to do.
  $mesg = $ldap->search(
                        base=> "cn=accesslog",
                        filter=>"(objectClass=*)",
                        scope => "base",
                        attrs => ['1.1'],
                 );
  $size = $mesg->count;
  if ($size == 0 ) {
    # Create accesslog db, add syncprov overlay, etc.
    File::Path::mkpath("${zimbra_home}/data/ldap/accesslog/db");
    $mesg=$ldap->add(
      $bdn,
      attr => [
        objectClass=>["olcDatabaseConfig","olcMdbConfig"],
        olcDatabase=>"{2}mdb",
        olcDbDirectory=>"${zimbra_home}/data/ldap/accesslog/db",
        olcSuffix=>"cn=accesslog",
        olcAccess=>'{0}to dn.subtree="cn=accesslog"  by dn.exact="uid=zimbra,cn=admins,cn=zimbra" read  by dn.exact="cn=config" read  by dn.exact="uid=zmreplica,cn=admins,cn=zimbra" read',
        olcLastMod=>"TRUE",
        olcMaxDerefDepth=>"15",
        olcReadOnly=>"FALSE",
        olcRootDN=>"cn=config",
        olcSizeLimit=>"unlimited",
        olcTimeLimit=>"unlimited",
        olcMonitoring=>"TRUE",
        olcDbCheckpoint=>"64 5",
        olcDbNoSync=>"FALSE",
        olcDbIndex=>["entryCSN eq", "objectClass eq", "reqEnd eq", "reqResult eq", "reqStart eq"],
        olcDbMode=>"0600",
        olcDbSearchStack=>"16",
	olcDbMaxsize=>"85899345920",
      ],
    );
    $mesg=$ldap->add(
      'olcOverlay=syncprov,olcDatabase={2}mdb,cn=config',
      attr => [
        objectClass=>["olcOverlayConfig", "olcSyncProvConfig"],
        olcOverlay=>"syncprov",
        olcSpNoPresent=>"TRUE",
        olcSpReloadHint=>"TRUE",
      ],
    );
    $mesg=>$ldap->add(
      'olcOverlay=syncprov,olcDatabase={3}mdb,cn=config',
      attr => [
        objectClass=>['olcOverlayConfig','olcSyncProvConfig'],
        olcOverlay=>'syncprov',
        olcSpCheckpoint=>'20 10',
      ],
    );
    $mesg=>$ldap->add(
      'olcOverlay=accesslog,olcDatabase={3}mdb,cn=config',
      attr => [
        objectClass=>['olcOverlayConfig','olcAccessLogConfig'],
        olcOverlay=>'accesslog',
        olcAccessLogDB=>'cn=accesslog',
        olcAccessLogOps=>'writes',
        olcAccessLogSuccess=>'TRUE',
        olcAccessLogPurge=>'01+00:00  00+04:00',
      ],
    );
  }
  $bdn="olcDatabase={3}mdb,cn=config";
  if ($mmrURI =~ /^ldaps:/) {
    $mesg = $ldap->modify(
      $bdn,
      add=>{olcSyncrepl=>"rid=$rid provider=$mmrURI bindmethod=simple timeout=0 network-timeout=0 binddn=uid=zmreplica,cn=admins,cn=zimbra credentials=$ldap_replication_password filter=\"(objectclass=*)\" searchbase=\"\" logfilter=\"(&(objectClass=auditWriteObject)(reqResult=0))\" logbase=cn=accesslog scope=sub schemachecking=off type=refreshAndPersist retry=\"60 +\" syncdata=accesslog tls_cacertdir=/opt/zimbra/conf/ca keepalive=240:10:30"},
    );
  } elsif ($ldap_starttls_supported && $zimbra_require_interprocess_security) {
    $mesg = $ldap->modify(
      $bdn,
      add=>{olcSyncrepl=>"rid=$rid provider=$mmrURI bindmethod=simple timeout=0 network-timeout=0 binddn=uid=zmreplica,cn=admins,cn=zimbra credentials=$ldap_replication_password starttls=critical filter=\"(objectclass=*)\" searchbase=\"\" logfilter=\"(&(objectClass=auditWriteObject)(reqResult=0))\" logbase=cn=accesslog scope=sub schemachecking=off type=refreshAndPersist retry=\"60 +\" syncdata=accesslog tls_cacertdir=/opt/zimbra/conf/ca keepalive=240:10:30"},
    );
  } else {
    $mesg = $ldap->modify(
      $bdn,
      add=>{olcSyncrepl=>"rid=$rid provider=$mmrURI bindmethod=simple timeout=0 network-timeout=0 binddn=uid=zmreplica,cn=admins,cn=zimbra credentials=$ldap_replication_password filter=\"(objectclass=*)\" searchbase=\"\" logfilter=\"(&(objectClass=auditWriteObject)(reqResult=0))\" logbase=cn=accesslog scope=sub schemachecking=off type=refreshAndPersist retry=\"60 +\" syncdata=accesslog tls_cacertdir=/opt/zimbra/conf/ca keepalive=240:10:30"},
    );
  }
  $mesg = $ldap ->search(
                    base=>"$bdn",
                    filter=>"(&(objectClass=olcMdbConfig)(olcMirrorMode:booleanMatch:=TRUE))",
                    scope=>"sub",
                    attrs => ['olcMirrorMode'],
                );
  $size = $mesg->count;
  if ($size == 0 ) {
    $mesg = $ldap->modify(
      $bdn,
      replace=>{olcMirrorMode=>"TRUE"},
    );
  }
} else {
  print "Not a master, please use zmldappromote-replica-mmr\n";
  exit(0);
}

sub usage {

        my ($msg) = (@_);

        $msg && print STDERR "\nERROR: $msg\n";
        print STDERR <<USAGE;
  zmldapenable-mmr [-r RID] [-s SID] -m MMRURI

  Where:
  RID is a unique Integer Replication ID for this replication instance.  It must be unique inside this server.  Example: 100 Default: 100
  SID is an unique Integer Server ID for THIS LDAP Master.  It CANNOT be in use by any other LDAP master.  Example: 2
  MMRURI is the LDAP URI for an alternate master.  Example: ldap://ldap-master2.example.com:389/

USAGE
        exit (1);
}

