#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010 Zimbra, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 

#
if [ x`whoami` != "xzimbra" ]; then
  echo "Error: must be run as user zimbra"
  exit 1
fi

umask 027
source `dirname $0`/../bin/zmshutil || exit 1
zmsetvars \
        logger_data_directory

# Get the root directory for the logger db data and construct directory name to move old data to
logger_data_dir_base="`dirname ${logger_data_directory}`"
backup_logger_dir="`dirname ${logger_data_dir_base}`/`basename ${logger_data_dir_base}`-`date +%Y%m%d.%H%M`"
tmp_logger_dir="`dirname ${logger_data_dir_base}`/`basename ${logger_data_dir_base}`-tmp"

# Make the switchout action as atomic as possible.  So, prep new dir structures in "tmp" root logger data dir first.
mkdir -p ${tmp_logger_dir}/data/rrds ${tmp_logger_dir}/work
chmod 750 ${tmp_logger_dir}
chmod 755 ${tmp_logger_dir}/work
chmod 775 ${tmp_logger_dir}/data
chmod 750 ${tmp_logger_dir}/data/rrds
cp ${logger_data_dir_base}/work/*.gif ${tmp_logger_dir}/work/.

# Stop zmlogger, shuffle directories around, and restart zmlogger
zmloggerctl stop
mv ${logger_data_dir_base} ${backup_logger_dir}
mv ${tmp_logger_dir} ${logger_data_dir_base}
zmloggerctl start

exit 0
