#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# 
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007 Zimbra, Inc.
# 
# The contents of this file are subject to the Yahoo! Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# 
# ***** END LICENSE BLOCK *****
# 
#
# This script sets up ldap query filters used by postfix.
#

source `dirname $0`/../bin/zmshutil || exit 1
zmsetvars

case "$#" in
  0) 
   ;;
  1)
    ldap_host="$1"
    ldap_port=389
    ldap_url="ldap://${ldap_host}:${ldap_port}"
    ;;
  2)
    ldap_host="$1"
    ldap_port="$2"
    ldap_url="ldap://${ldap_host}:${ldap_port}"
    ;;
  *)
    echo Usage: `basename $0` ldap_host [ ldap_port ]
    exit
    ;;
esac
    


confdir=/opt/zimbra/conf
mkdir -p ${confdir}

cat<<EOF > ${confdir}/ldap-vmm.cf
server_host = ${ldap_url}
server_port = ${ldap_port}
search_base =
query_filter = (&(zimbraMailDeliveryAddress=%s)(zimbraMailStatus=enabled))
result_attribute = zimbraMailDeliveryAddress
version = 3
start_tls = yes
tls_ca_cert_dir = /opt/zimbra/conf/ca
bind = no
timeout = 30
EOF

cat<<EOF > ${confdir}/ldap-vmd.cf
server_host = ${ldap_url}
server_port = ${ldap_port}
search_base =
query_filter = (&(zimbraDomainName=%s)(zimbraDomainType=local)(zimbraMailStatus=enabled))
result_attribute = zimbraDomainName
version = 3
start_tls = yes
tls_ca_cert_dir = /opt/zimbra/conf/ca
bind = no
timeout = 30
EOF

cat<<EOF > ${confdir}/ldap-vam.cf
server_host = ${ldap_url}
server_port = ${ldap_port}
search_base =
query_filter = (&(|(zimbraMailDeliveryAddress=%s)(zimbraMailAlias=%s)(zimbraMailCatchAllAddress=%s))(zimbraMailStatus=enabled))
result_attribute = zimbraMailDeliveryAddress,zimbraMailForwardingAddress,zimbraPrefMailForwardingAddress,zimbraMailCatchAllForwardingAddress
version = 3
start_tls = yes
tls_ca_cert_dir = /opt/zimbra/conf/ca
bind = no
timeout = 30
EOF

cat<<EOF > ${confdir}/ldap-vad.cf
server_host = ${ldap_url}
server_port = ${ldap_port}
search_base =
query_filter = (&(zimbraDomainName=%s)(zimbraDomainType=alias)(zimbraMailStatus=enabled))
result_attribute = zimbraDomainName
version = 3
start_tls = yes
tls_ca_cert_dir = /opt/zimbra/conf/ca
bind = no
timeout = 30
EOF

cat<<EOF > ${confdir}/ldap-scm.cf
server_host = ${ldap_url}
server_port = ${ldap_port}
search_base = 
query_filter = (&(|(zimbraMailDeliveryAddress=%s)(zimbraMailAlias=%s)(zimbraMailCatchAllAddress=%s))(zimbraMailStatus=enabled))
result_attribute = zimbraMailCanonicalAddress,zimbraMailCatchAllCanonicalAddress
version = 3
start_tls = yes
tls_ca_cert_dir = /opt/zimbra/conf/ca
bind = no
timeout = 30
EOF

cat<<EOF > ${confdir}/ldap-transport.cf
server_host = ${ldap_url}
server_port = ${ldap_port}
search_base =
query_filter = (&(|(zimbraMailDeliveryAddress=%s)(zimbraDomainName=%s))(zimbraMailStatus=enabled))
result_attribute = zimbraMailTransport
version = 3
start_tls = yes
tls_ca_cert_dir = /opt/zimbra/conf/ca
bind = no
timeout = 30
EOF
