#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2004, 2005, 2006, 2007, 2008, 2009, 2010 Zimbra, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 

source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars -f

#
#
# Usage: zmmycnf [--innodb-buffer-pool-memory-percent number].  
# 
# We don't error check - if you provide wrong arguments we default the
# buffer pool percent to keep things simple for the installer.
#
bufferPoolPercent=25
if [ "x$1" = "x--innodb-buffer-pool-memory-percent" ];
then
    if echo "$2" | grep -q "^[0-9]*$"
    then
        if [ $2 -gt 1 -a $2 -lt 100 ]; then
            bufferPoolPercent=$2
        fi
    fi
fi

#
# Calculate innodb buffer pool size
#
memKB=$(zmsysmemkb)
((bufferPoolSize=memKB * 1024 * bufferPoolPercent / 100))

#
# Tell the JDBC driver how many mysql active connections to use.
#
${zimbra_home}/bin/zmlocalconfig -e zimbra_mysql_connector_maxActive=100

#
# Write config to stdout
#
cat<<EOF

[mysqld]

basedir        = ${mysql_directory}
datadir        = ${mysql_data_directory}
socket         = ${mysql_socket}
pid-file       = ${mysql_pidfile}
bind-address   = ${mysql_bind_address}
port           = ${mysql_port}
user           = ${zimbra_mysql_user}
tmpdir         = ${zimbra_tmp_directory}
slow_query_log = ${zimbra_log_directory}/myslow.log

external-locking
log_slow_queries
ignore-builtin-innodb

plugin-load=innodb=ha_innodb_plugin.so;innodb_trx=ha_innodb_plugin.so;innodb_locks=ha_innodb_plugin.so;innodb_lock_waits=ha_innodb_plugin.so;innodb_cmp=ha_innodb_plugin.so;innodb_cmp_reset=ha_innodb_plugin.so;innodb_cmpmem=ha_innodb_plugin.so;innodb_cmpmem_reset=ha_innodb_plugin.so

log-short-format = FALSE
long-query-time  = 1
log-queries-not-using-indexes

thread_cache_size = 110
max_connections   = 110

# We do a lot of writes, query cache turns out to be not useful.
query_cache_type = 0

sort_buffer_size = 1048576
read_buffer_size = 1048576

# (Num mailbox groups * Num tables in each group) + padding
table_cache = 1200

innodb_buffer_pool_size        = ${bufferPoolSize}
innodb_log_file_size           = 104857600
innodb_log_buffer_size         = 8388608
innodb_file_per_table

# Value is: 200 + max_connections + 2 * table_cache
innodb_open_files              = 2710

innodb_max_dirty_pages_pct     = 10
innodb_flush_method            = O_DIRECT
innodb_flush_log_at_trx_commit = 0

[mysqld_safe]

err-log      = ${zimbra_log_directory}/mysqld.log
pid-file     = ${mysql_pidfile}


EOF
