#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# 
# Zimbra Collaboration Suite Server
# Copyright (C) 2004, 2005, 2006, 2007 Zimbra, Inc.
# 
# The contents of this file are subject to the Yahoo! Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# 
# ***** END LICENSE BLOCK *****
# 

source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars

#
# Memory for use by MySQL.
#
memkb=$(zmsysmemkb)
((mymem=memkb * 1024 * mysql_memory_percent / 100))

#
# Allocate 75% of memory that mysql can use to buffer pool.
#
((computed_innodb_buffer_pool_size = mymem * 75 / 100))

#
# Tell the JDBC driver how many mysql active connections to use.
#
${zimbra_home}/bin/zmlocalconfig -e zimbra_mysql_connector_maxActive=100

#
# Write config to stdout
#
cat<<EOF

[mysqld]

basedir      = ${mysql_directory}
datadir      = ${mysql_data_directory}
socket       = ${mysql_socket}
pid-file     = ${mysql_pidfile}
bind-address = ${mysql_bind_address}
port         = ${mysql_port}
user         = ${zimbra_mysql_user}

external-locking

log-slow-queries = ${zimbra_log_directory}/myslow.log
long-query-time  = 1
log-long-format
log-queries-not-using-indexes

thread_cache      = 110
max_connections   = 110

# We do a lot of writes, query cache turns out to be not useful.
query_cache_type = 0

sort_buffer_size = ${mysql_sort_buffer_size}
read_buffer_size = ${mysql_read_buffer_size}

# Increase the size of the table cache, since each mailbox has its
# own set of tables
table_cache = ${mysql_table_cache}

innodb_buffer_pool_size   = ${computed_innodb_buffer_pool_size}
innodb_log_file_size      = ${mysql_innodb_log_file_size}
innodb_log_buffer_size    = ${mysql_innodb_log_buffer_size}
innodb_file_per_table
innodb_open_files         = ${mysql_table_cache}

[mysqld_safe]

err-log      = ${zimbra_log_directory}/mysqld.log
pid-file     = ${mysql_pidfile}


EOF
