#!/usr/bin/perl
# 
# ***** BEGIN LICENSE BLOCK *****
# 
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006 Zimbra, Inc.
# 
# The contents of this file are subject to the Yahoo! Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# 
# ***** END LICENSE BLOCK *****
# 

use strict;

use lib "/opt/zimbra/zimbramon/lib";
use Zimbra::Util::Common;

use LWP::UserAgent;

my $baseDir = "/opt/zimbra";

my $version = $ARGV[0];
my $email = $ARGV[1];

my $URL = "http://www.zimbra.com/cgi-bin/notify.cgi?VER=$version&MAIL=$email";

print "Notifying Zimbra of installation via $URL\n\n";

# Create a user agent object
my $ua = LWP::UserAgent->new;
$ua->agent("ZimbraInstaller/0.1 ");

# Create a request
my $req = HTTP::Request->new(GET => "$URL");

# Pass request to the user agent and get a response back
my $res = $ua->request($req);

# Check the outcome of the response
if ($res->is_success) {
	print "Notification complete\n\n";
} else {
	print "ERROR: Notification failed ";
	print $res->{status_line};
	print "\n";
}

exit (0);
