#!/usr/bin/perl
# 
# ***** BEGIN LICENSE BLOCK *****
# 
# Zimbra Collaboration Suite Server
# Copyright (C) 2006 Zimbra, Inc.
# 
# The contents of this file are subject to the Yahoo! Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# 
# ***** END LICENSE BLOCK *****
# 

use strict;

if ($#ARGV != 2) {
    print STDERR "Usage: zmqaction action queuename queuid1[,queueid2]+\n";
    exit(1);
}

my $action = $ARGV[0];
my $queue = $ARGV[1];
my $idarg = $ARGV[2];

my $paction;
if ($action eq "hold") {
    $paction = "-h";
} elsif ($action eq "release") {
    $paction = "-H";
} elsif ($action eq "requeue") {
    $paction = "-r";
} elsif ($action eq "delete") {
    $paction = "-d";
} else {
    print STDERR "ERROR: unknown action $action\n";
    exit(1);
}


if ($queue !~ /^(incoming|active|deferred|hold|maildrop|corrupt)$/) {
    print STDERR "ERROR: unknown queue $queue\n";
    exit(1);
}

if ($idarg eq "ALL") {
    system("sudo /opt/zimbra/postfix/sbin/postsuper $paction ALL $queue");
} else {
    my @ids = split(',', $idarg);
    my $command = "sudo /opt/zimbra/postfix/sbin/postsuper $paction - $queue";
    if (open(POSTSUPER, "| $command")) {
        foreach my $id (@ids) {
            print POSTSUPER $id, "\n";
        }
        close(POSTSUPER);
    } else {
        print STDERR "ERROR: command $command: $!\n";
        exit(1);
    }
}
