#!/usr/bin/perl
# 
# ***** BEGIN LICENSE BLOCK *****
# 
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006 Zimbra, Inc.
# 
# The contents of this file are subject to the Yahoo! Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# 
# ***** END LICENSE BLOCK *****
# 

my $desthost=$ARGV[0];

shift;

my $keyfile="/opt/zimbra/.ssh/zimbra_identity";

if ($desthost eq "") {
	print "Usage: $0 <hostname>\n";
	exit 1;
}

if ($#ARGV >= 0) {
	$cmd = "echo @ARGV | ssh -T -i ${keyfile} -o StrictHostKeyChecking=no zimbra\@${desthost}";
} else {
	$cmd = "ssh -T -i ${keyfile} -o StrictHostKeyChecking=no zimbra\@${desthost}";
}

open P, "$cmd |";
$SIG{ALRM} = \&quit;
while (<P>) {print $_; alarm(10);}
close P;

sub quit {
	exit 0;
}
