#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2004, 2005, 2006, 2007, 2008, 2009, 2010 Zimbra, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 

if [ x`whoami` != "xzimbra" ]; then
  echo "Error: must be run as user zimbra"
  exit 1
fi

usage() {
  echo "$0 [--help] [--sql_root_pw <password>] [--mysql_memory_percent 30]"
  echo "  --sql_root_pw defaults to random password if not specified."
  echo "  --mysql_memory_percent defaults to 30 percent if not specified."
}

source `dirname $0`/../bin/zmshutil || exit 1
zmsetvars -f

#
# Sanity checks
#
zmassert -x ${zimbra_home}/bin/mysqladmin
zmassert -x ${zimbra_home}/bin/mysql
zmassert -x ${zimbra_home}/bin/zmlocalconfig
zmassert -x ${zimbra_home}/bin/zmcontrol
zmassert -r ${zimbra_db_directory}/db.sql
if [ ! -x ${zimbra_home}/mysql/bin/mysql ]; then
  echo "Mysql not found on this host."
  exit 1
fi

usage() {
  echo "$0 [-help] password"
}

ask() {
  PROMPT=$1
  DEFAULT=$2

  echo ""
  echo -n "$PROMPT [$DEFAULT] "
  read response

  if [ -z $response ]; then
    response=$DEFAULT
  fi
}
askYN() {
  PROMPT=$1
  DEFAULT=$2

  if [ "x$DEFAULT" = "xyes" -o "x$DEFAULT" = "xYes" -o "x$DEFAULT" = "xy" -o "x$DEFAULT" = "xY" ]; then
    DEFAULT="Y"
  else
    DEFAULT="N"
  fi

  while [ 1 ]; do
    ask "$PROMPT" "$DEFAULT"
    response=$(perl -e "print lc(\"$response\");")
    if [ -z $response ]; then
      :
    else
      if [ $response = "yes" -o $response = "y" ]; then
        response="yes"
        break
      else
        if [ $response = "no" -o $response = "n" ]; then
          response="no"
          break
        fi
      fi
    fi
    echo "A Yes/No answer is required"
  done
}

for opt in "$@"; do
  case "$opt" in
    -help|--help|-h|--help)
      usage
      exit 0
      shift
      ;;
    --*|-*)
      echo "Unknown option $opt"
      usage
      exit 1
      shift
      ;;
    *)
      password=$1
      shift
      ;;
  esac
done



if [ x"$password" = "x" ]; then
  usage
  exit 1
fi

askYN "WARNING: All zimbra services will be stopped.  Would you like to continue?" "N"
if [ $response != "yes" ]; then
  echo "All services must be stopped in order to reset mysql password. Exiting."
  exit
fi

${zimbra_home}/bin/zmcontrol stop

echo "Starting mysqld"
cd ${mysql_directory}; ${mysql_directory}/bin/mysqld_safe --defaults-file=${mysql_mycnf} --skip-grant-tables --ledir=${mysql_directory}/libexec &
sleep 10

echo "Changing zimbra passwd"
${zimbra_home}/bin/mysql -Dmysql -P ${mysql_port} -e "update user set password=PASSWORD(\"$password\") where user = 'zimbra';"
${zimbra_home}/bin/zmlocalconfig -f -e zimbra_mysql_password=$password

echo "Changing root passwd"
${zimbra_home}/bin/mysql -Dmysql -P ${mysql_port} -e "update user set password=PASSWORD(\"$password\") where user = 'root';"
${zimbra_home}/bin/zmlocalconfig -f -e mysql_root_password=$password

echo "Flushing privileges";
${zimbra_home}/bin/mysql -Dmysql -P ${mysql_port} -e "flush privileges;"
${zimbra_home}/bin/mysql.server stop

echo "Restarting zimbra services"
${zimbra_home}/bin/zmcontrol start
