#!/usr/bin/perl -w
# 
# ***** BEGIN LICENSE BLOCK *****
# 
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007 Zimbra, Inc.
# 
# The contents of this file are subject to the Yahoo! Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# 
# ***** END LICENSE BLOCK *****
# 

use strict;
use Getopt::Long;

my @interfaces = ();
open INTS, "/sbin/ifconfig | grep 'inet ' |";
foreach (<INTS>) {
  chomp;
  s/.*inet //;
  s/\s.*//;
  s/[a-zA-Z:]//g;
  next if /^$/;
  push @interfaces, $_;
}
close INTS;
my %seen;
if (scalar @interfaces) {
  foreach (@interfaces) {
    $seen{$_}++;
    print "$_\n" unless ($seen{$_} > 1);
  }
}

#/sbin/ifconfig | grep '	inet ' | sed -e 's/.*inet //' -e 's/\s.*//' -e 's/[a-zA-Z:]//g' | uniq 
#/sbin/ifconfig | sed -e '/^[ 	] *inet /!d' -e 's/.*inet //' -e 's/\s.*//' -e 's/[a-zA-Z:]//g' | uniq 
