#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Version: MPL 1.1
# 
# The contents of this file are subject to the Mozilla Public License
# Version 1.1 ("License"); you may not use this file except in
# compliance with the License. You may obtain a copy of the License at
# http://www.zimbra.com/license
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
# the License for the specific language governing rights and limitations
# under the License.
# 
# The Original Code is: Zimbra Collaboration Suite Server.
# 
# The Initial Developer of the Original Code is Zimbra, Inc.
# Portions created by Zimbra are Copyright (C) 2005, 2006, 2007 Zimbra, Inc.
# All Rights Reserved.
# 
# Contributor(s):
# 
# ***** END LICENSE BLOCK *****
# 

source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars \
	zimbra_home 

u=`id -un`
if [ $u != ${zimbra_user} ]; then
    echo "Error: must be run as ${zimbra_user} user"
    exit 1
fi

if [[ ! -L ${zimbra_home}/openldap && ! -d ${zimbra_home}/openldap ]]; then
	# No ldap - exit gracefully
	exit 0
fi

if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
	echo "USAGE: zmslapcat <DIR>"
	exit 1
fi
DEST=$1

mkdir -p $DEST

D=`date +%Y%m%d%H%M%S`
${zimbra_home}/openldap/sbin/slapcat -f ${zimbra_home}/conf/slapd.conf > $DEST/ldap.bak.${D}
cp -f ${DEST}/ldap.bak.${D} ${DEST}/ldap.bak
