#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2012, 2013 Zimbra Software, LLC.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.4 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
ulimit -n 32768
ulimit -c unlimited
ulimit -v unlimited
export LD_PRELOAD=/opt/zimbra/tcmalloc/lib/libtcmalloc_minimal.so

umask 027
source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars \
	zimbra_home 

if [ ! -x /opt/zimbra/openldap/sbin/slapadd ]; then
	exit 0
fi

u=`id -un`
if [ $u != ${zimbra_user} ]; then
    echo "Error: must be run as ${zimbra_user} user"
    exit 1
fi

zgood=no
bgood=no
zcat=`which zcat 2>/dev/null`
bzcat=`which bzcat 2>/dev/null`

if [ -x $zcat ]; then
	zgood=yes
fi

if [ -x $bzcat ]; then
	bgood=yes
fi

if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
	echo "USAGE: Imports LDAP databases"
	echo "Main database: zmslapadd <FILE>"
	echo "Config database: zmslapadd -c <FILE>"
	echo "Accesslog database: zmslapadd -a <FILE>"
	exit 1
fi

CONFIG=no
ALOG=no
if [ x$1 = "x-c" ]; then
	CONFIG=yes
	SRC=$2
elif [ x$1 = "x-a" ]; then
	ALOG=yes
	SRC=$2
else
	SRC=$1
fi

comp=0
computil=

if [ ! -f $SRC ]; then
	echo "Error: Input file does not exist"
	exit 1
fi

if [[ "$SRC" == *".gz" ]]; then
	if [ x$zgood = "xno" ]; then
		echo "Error: zcat is missing."
		exit 1
	fi
	computil=$zcat
	comp=1
elif [[ "$SRC" == *".bz2" ]]; then
	if [ x$bgood = "xno" ]; then
		echo "Error: bzcat is missing."
		exit 1
	fi
	computil=$bzcat
	comp=1
fi

if [ x$CONFIG = "xyes" ]; then
	if [ x$comp = "x0" ]; then
		${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -n 0 -l $SRC
		RETVAL=$?
	else
		$computil $SRC | ${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -n 0
		RETVAL=$?
	fi
elif [ x$ALOG = "xyes" ]; then
	if [ x$comp = "x0" ]; then
		${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -b "cn=accesslog" -l $SRC
		RETVAL=$?
	else
		$computil $SRC | ${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -b "cn=accesslog"
		RETVAL=$?
	fi
else
	if [ x$comp = "x0" ]; then
		${zimbra_home}/openldap/sbin/slapadd -w -q -F ${zimbra_home}/data/ldap/config -b "" -l $SRC
		RETVAL=$?
	else
		$computil $SRC | ${zimbra_home}/openldap/sbin/slapadd -w -q -F ${zimbra_home}/data/ldap/config -b ""
		RETVAL=$?
	fi
fi

exit $RETVAL
