#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# 
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007 Zimbra, Inc.
# 
# The contents of this file are subject to the Yahoo! Public License
# Version 1.0 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# 
# ***** END LICENSE BLOCK *****
# 
umask 027
source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars \
	zimbra_home 

u=`id -un`
if [ $u != ${zimbra_user} ]; then
    echo "Error: must be run as ${zimbra_user} user"
    exit 1
fi

if [[ ! -L ${zimbra_home}/openldap && ! -d ${zimbra_home}/openldap ]]; then
	# No ldap - exit gracefully
	exit 0
fi

if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
	echo "USAGE: zmslapcat <DIR>"
	exit 1
fi
DEST=$1

mkdir -p $DEST

D=`date +%Y%m%d%H%M%S`
${zimbra_home}/openldap/sbin/slapcat -f ${zimbra_home}/conf/slapd.conf -b "" -l $DEST/ldap.bak.${D}
cp -f ${DEST}/ldap.bak.${D} ${DEST}/ldap.bak

