#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010, 2012, 2013 Zimbra Software, LLC.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.4 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
ulimit -n 32768
ulimit -c unlimited
ulimit -v unlimited
export LD_PRELOAD=/opt/zimbra/tcmalloc/lib/libtcmalloc_minimal.so

umask 027
source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars \
	zimbra_home 

if [ ! -x /opt/zimbra/openldap/sbin/slapcat ]; then
	exit 0
fi

u=`id -un`
if [ $u != ${zimbra_user} ]; then
    echo "Error: must be run as ${zimbra_user} user"
    exit 1
fi

if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
	echo "USAGE: Exports LDAP databases"
	echo "Main database: zmslapcat <DIR>"
	echo "Config database: zmslapcat -c <DIR>"
	echo "Accesslog database: zmslapcat -a <DIR>"
	exit 1
fi

D=`date +%Y%m%d%H%M%S`
CONFIG=no
FILE=ldap.bak.${D}
NFILE=ldap.bak
if [ x$1 = "x-c" ]; then
	CONFIG=yes
	FILE=ldap-config.bak.${D}
	NFILE=ldap-config.bak
	DEST=$2
elif [ x$1 = "x-a" ]; then
	ALOG=yes
	FILE=ldap-accesslog.bak.${D}
	NFILE=ldap-accesslog.bak
	DEST=$2
else
	DEST=$1
fi

mkdir -p $DEST
RC=0
if [ x$CONFIG = "xyes" ]; then
	${zimbra_home}/openldap/sbin/slapcat -F ${zimbra_home}/data/ldap/config -n 0 -l ${DEST}/${FILE}
	RC=$?
elif [ x$ALOG = "xyes" ]; then
	${zimbra_home}/openldap/sbin/slapcat -F ${zimbra_home}/data/ldap/config -b "cn=accesslog" -l ${DEST}/${FILE}
	RC=$?
else
	${zimbra_home}/openldap/sbin/slapcat -F ${zimbra_home}/data/ldap/config -b "" -l ${DEST}/${FILE}
	RC=$?
fi

cp -f ${DEST}/${FILE} ${DEST}/${NFILE}
exit $RC
