#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007, 2008, 2009, 2010 Zimbra, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 
ulimit -n 32768
ulimit -c unlimited
ulimit -v unlimited
export LD_PRELOAD=/opt/zimbra/tcmalloc/lib/libtcmalloc_minimal.so

umask 027
source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars \
	zimbra_home 

if [ ! -x /opt/zimbra/openldap/sbin/slapadd ]; then
	exit 0
fi

u=`id -un`
if [ $u != ${zimbra_user} ]; then
    echo "Error: must be run as ${zimbra_user} user"
    exit 1
fi

if [ x$1 = "x" -o x$1 = "x-h" -o x$1 = "x--help" ]; then
	echo "USAGE: Imports LDAP databases"
	echo "Main database: zmslapadd <DIR>"
	echo "Config database: zmslapadd -c <DIR>"
	echo "Accesslog database: zmslapadd -a <DIR>"
	exit 1
fi

D=`date +%Y%m%d%H%M%S`
CONFIG=no
ALOG=no
if [ x$1 = "x-c" ]; then
	CONFIG=yes
	SRC=$2
elif [ x$1 = "x-a" ]; then
	ALOG=yes
	SRC=$2
else
	SRC=$1
fi

if [ x$CONFIG = "xyes" ]; then
	${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -n 0 -l $SRC
	RETVAL=$?
elif [ x$ALOG = "xyes" ]; then
	${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -b "cn=accesslog" -l $SRC
	RETVAL=$?
else
	${zimbra_home}/openldap/sbin/slapadd -q -F ${zimbra_home}/data/ldap/config -b "" -l $SRC
	RETVAL=$?
fi

exit $RETVAL
