#!/usr/bin/perl
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2008, 2009, 2010 Zimbra, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 

use strict;

if (scalar(@ARGV) != 1) {
  print(STDERR "Usage: install-openldap <p4-branch-name>\n");
  exit(1);
}

my $BASE_DIR = "/opt/zimbra";
my $CACHE_DIR = "$BASE_DIR/third-party-cache";
my $P4_ROOT = "//depot/$ARGV[0]/ThirdPartyBuilds/" . getPlatformDirName();
my %BINARIES = (
                "bdb" => "4.7.25.4",
                "curl" => "7.19.7",
                "cyrus-sasl" => "2.1.23.3z",
                "heimdal" => "1.3.1",
                "libtool" => "2.2.6b",
                "openldap" => "2.4.21.3z",
                "openldap-libs" => "2.4.21.3z",
                "openssl" => "0.9.8l",
                "tcmalloc" => "1.4"
               );
my $P4_CMD = "p4";

if (! -d $CACHE_DIR) {
  mkdir($CACHE_DIR) || die "Could not create directory: $CACHE_DIR";
}

for my $binaryName (keys %BINARIES) {
  my $version = $BINARIES{$binaryName};
  my $cmd;
  my $p4Path;

  if ($binaryName eq "openldap-libs") {
      $p4Path = "$P4_ROOT/openldap/openldap-libs-$version.tgz";
  } else {
      $p4Path = "$P4_ROOT/$binaryName/$binaryName-$version.tgz";
  }

  # Copy tarball to the third party cache directory if necessary.
  my $tarball = "$CACHE_DIR/$binaryName-$version.tgz";
  if (! -f $tarball) {
      $cmd = "$P4_CMD print -o $tarball $p4Path";
      runCommand($cmd);
  }

  # Untar
  $cmd = "tar -xzf $tarball -C $BASE_DIR";
  runCommand($cmd);

  if ($binaryName ne "openldap-libs") {
      # Replace existing symlink.
      $cmd = "rm -f $BASE_DIR/$binaryName";
      runCommand($cmd);
      symlink("$BASE_DIR/$binaryName-$version", "$BASE_DIR/$binaryName") || die "Could not create symlink for $binaryName";
  }
}

sub runCommand($) {
    my $cmd = shift();
    print("$cmd\n");
    system($cmd);
    if ($? != 0) {
	print(STDERR "An error occurred while running '$cmd'");
	if (defined($!)) {
	    print(STDERR ": $!");
	}
	print(STDERR "\n");
	exit(1);
    }
}

sub getPlatformDirName() {
    my $os = `uname -s`;
    chomp($os);
    my $dirName;
    
    if ($os eq "Darwin") {
	my $version = `uname -r | cut -f1 -d.`;
	chomp($version);
	if ($version eq "8") {
	    $dirName = "MACOSXx86";
	} else {
	    $dirName = "MACOSXx86_10.5";
	}
    } else {
	if (-f "/etc/redhat-release") {
	    my $uname = `uname -a`;
	    if ($uname =~ /release 5/) {
		if ($uname =~ /64/) {
		    $dirName = "RHEL5_64";
		} else {
		    $dirName = "RHEL5";
		}
	    } else {
		if ($uname =~ /64/) {
		    $dirName = "RHEL4_64";
		} else {
		    $dirName = "RHEL4";
		}
	    }
	} else {
	    $dirName = "UBUNTU8";
	}
    }

    return $dirName;
}
