/**
 * PLEASE DO NOT MODIFY IT MANUALLY!
 * 
 * This file should be autogenerated by the program
 * against zimbra-rights.xml .
 *
 * It is Javascript version of zimbra-rights.xml
 *
 * ZaZimbraRights is a JSON representation of zimbra-rights
 *
 *
 */

ZaZimbraRights = {} ;

/* Can build index here using the program */
ZaZimbraRights.type = [
    "preset", "getAttrs", "setAttrs", "combo"
]

ZaZimbraRights.targetType = [
    "account", "distributionlist", "resource", "domain" ,
    "cos" , "server", "config" , "global", "combo"    
]

ZaZimbraRights ["preset"] = {} ;
ZaZimbraRights ["preset"] ["accounts"] = [] ;
ZaZimbraRights ["preset"] ["accounts"] =


ZaZimbraRights.JSON = [
//  User Rights
    {
        name: "invite",
        userRights: "1",
        desc: com_zimbra_delegatedadmin.rights_desc_invite
    },

// Admin rights
    {
        name: "createAccount",
        type: "preset" ,
        targetType: "domain",
        desc: com_zimbra_delegatedadmin.rights_desc_createAccount
    },
    {
        name: "renameServer",
        type: "preset" ,
        targetType: "server",
        desc: com_zimbra_delegatedadmin.rights_desc_renameServer
    }
]