// MapiExchange.idl : IDL source for MapiExchange
//

// This file will be processed by the MIDL tool to
// produce the type library (MapiExchange.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(D5FD1423-78B7-4DCF-A293-88B24F96B098),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IExchangeMigObject : IDispatch{
	[id(1), helpstring("The 1st method to be called to use the migration object")] HRESULT InitializeMigration([in] BSTR ConfigXMLFileName, [in] BSTR UserMapFileName);
	[id(2), helpstring("The method used for logging on to the mail server")] HRESULT ConnectToserver(void);
	[id(3), helpstring("The method used for importing the options configured in the xml file")] HRESULT ImportMailoptions(void);
};
[
	uuid(08C8DADF-74E0-4BD5-8D37-CA8CFAACCE89),
	version(1.0),
]
library MapiExchangeLib
{
	importlib("stdole2.tlb");
	[
		uuid(B3D2EE09-6B18-4327-9F91-6C940E97997D)		
	]
	coclass ExchangeMigObject
	{
		[default] interface IExchangeMigObject;
	};
};

