/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Connector base version */
#define BASE_VERSION "2.6"

/* No deprecated bonobo functions */
#define BONOBO_DISABLE_DEPRECATED 1

/* No deprecated bonoboui functions */
#define BONOBO_UI_DISABLE_DEPRECATED 1

/* Package name for gettext */
#define CAMEL_EXPLICIT_TRANSLATION_DOMAIN "evolution-zimbra-2.6"

/* always defined to indicate that i18n is enabled */
#define ENABLE_NLS 1

/* Evolution version */
#define EVOLUTION_BASE_VERSION "2.6"

/* No deprecated gconf functions */
#define GCONF_DISABLE_DEPRECATED 1

/* No deprecated gdk functions */
#define GDK_DISABLE_DEPRECATED 1

/* Package name for gettext */
#define GETTEXT_PACKAGE "evolution-zimbra-2.6"

/* Do not log */
#define GLOG_DISABLE_LOGGING 1

/* No deprecated gnome functions */
#define GNOME_DISABLE_DEPRECATED 1

/* No deprecated gtk functions */
#define GTK_DISABLE_DEPRECATED 1

/* No deprecated glib functions */
#define G_DISABLE_DEPRECATED 1

/* Define if libc defines an altzone variable */
/* #undef HAVE_ALTZONE */

/* Define to 1 if you have the `bind_textdomain_codeset' function. */
#define HAVE_BIND_TEXTDOMAIN_CODESET 1

/* Define to 1 if you have the `dcgettext' function. */
#define HAVE_DCGETTEXT 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define if the GNU gettext() function is already present or preinstalled. */
#define HAVE_GETTEXT 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the `isblank' function. */
#define HAVE_ISBLANK 1

/* Define if your <locale.h> file defines LC_MESSAGES. */
#define HAVE_LC_MESSAGES 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the `mkdtemp' function. */
#define HAVE_MKDTEMP 1

/* Define to 1 if you have the `mkstemp' function. */
#define HAVE_MKSTEMP 1

/* Defined if we have register_printf_function () */
#define HAVE_PRINTF_EXTENSION 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define if libc defines a timezone variable */
/* #undef HAVE_TIMEZONE */

/* Define if struct tm has a tm_gmtoff member */
#define HAVE_TM_GMTOFF 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* No deprecated libglade functions */
#define LIBGLADE_DISABLE_DEPRECATED 1

/* Name of package */
#define PACKAGE "evolution-zimbra"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT ""

/* Define to the full name of this package. */
#define PACKAGE_NAME ""

/* Define to the full name and version of this package. */
#define PACKAGE_STRING ""

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME ""

/* Define to the version of this package. */
#define PACKAGE_VERSION ""

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.1.0"
