#!/bin/sh
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2008, 2009, 2010 Zimbra, Inc.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.3 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 

status=`head -1 "$1/update.status"`
if [ ! "$status" = "applying" ]; then
  echo WRONG STATUS: $status >> "$1/update.log"
  exit 1
fi

if [ ! -r "$1/update.mar" ]; then
  echo UPDATE FILE NOT FOUND >> "$1/update.log"
  exit 1
fi

#get parameters for installer
parmfile="$1/../../update.params"
params=" "
if [ -r "$parmfile" ]; then
  while [ 1 ]; do
    read line || break
    params="$params $line"
  done < "$parmfile"
fi

echo Start updating... >> "$1/update.log"

stage=/tmp/zdupdate

rm -fr $stage
mkdir -p $stage
mv "$1/update.mar" $stage/update.dmg
/usr/bin/hdiutil attach $stage/update.dmg -mountpoint $stage/install
"$stage/install/Zimbra Desktop Installer.app/Contents/MacOS/JavaApplicationStub" $params
/usr/bin/hdiutil detach $stage/install
rm -fr $stage

echo Done updating >> "$1/update.log"
