package com.zimbra.qa.selenium.projects.html;

import com.zimbra.qa.selenium.projects.html.clients.Appointment;
import com.zimbra.qa.selenium.projects.html.clients.BriefcaseItem;
import com.zimbra.qa.selenium.projects.html.clients.BrowseFileField;
import com.zimbra.qa.selenium.projects.html.clients.Button;
import com.zimbra.qa.selenium.projects.html.clients.ButtonMenu;
import com.zimbra.qa.selenium.projects.html.clients.CalendarFolder;
import com.zimbra.qa.selenium.projects.html.clients.CalendarGrid;
import com.zimbra.qa.selenium.projects.html.clients.CheckBox;
import com.zimbra.qa.selenium.projects.html.clients.ContactListItem;
import com.zimbra.qa.selenium.projects.html.clients.Dialog;
import com.zimbra.qa.selenium.projects.html.clients.DocumentPage;
import com.zimbra.qa.selenium.projects.html.clients.Editfield;
import com.zimbra.qa.selenium.projects.html.clients.Editor;
import com.zimbra.qa.selenium.projects.html.clients.FeatureMenu;
import com.zimbra.qa.selenium.projects.html.clients.Folder;
import com.zimbra.qa.selenium.projects.html.clients.HtmlMenu;
import com.zimbra.qa.selenium.projects.html.clients.ListItem;
import com.zimbra.qa.selenium.projects.html.clients.MenuItem;
import com.zimbra.qa.selenium.projects.html.clients.MessageItem;
import com.zimbra.qa.selenium.projects.html.clients.MiscObject;
import com.zimbra.qa.selenium.projects.html.clients.PwdField;
import com.zimbra.qa.selenium.projects.html.clients.RadioBtn;
import com.zimbra.qa.selenium.projects.html.clients.Tab;
import com.zimbra.qa.selenium.projects.html.clients.TaskFolder;
import com.zimbra.qa.selenium.projects.html.clients.TaskItem;
import com.zimbra.qa.selenium.projects.html.clients.TextArea;
import com.zimbra.qa.selenium.projects.html.clients.ToastAlertMessage;

public class CoreObjects {
	public static Button zButton = new Button();
	public static FeatureMenu zFeatureMenu = new FeatureMenu();
	public static Appointment zAppointment = new Appointment();
	public static DocumentPage zDocumentPage = new DocumentPage();
	public static Folder zFolder = new Folder();
	public static ButtonMenu zButtonMenu = new ButtonMenu();
	public static MenuItem zMenuItem = new MenuItem();
	public static Dialog zDialog = new Dialog();
	public static MessageItem zMessageItem = new MessageItem();
	public static BriefcaseItem zBriefcaseItem = new BriefcaseItem();
	public static TaskItem zTaskItem = new TaskItem();
	public static TaskFolder zTaskFolder = new TaskFolder();
	public static Tab zTab =  new Tab();
	public static Editfield zEditField = new Editfield();
	public static TextArea zTextAreaField = new TextArea();
	public static Editor zEditor = new Editor();
	public static PwdField zPwdField = new PwdField();
	public static CheckBox zCheckbox = new CheckBox();
	public static RadioBtn zRadioBtn = new RadioBtn();
	public static BrowseFileField zBrowseField = new BrowseFileField();
	public static ContactListItem zContactListItem = new ContactListItem();
	public static ToastAlertMessage zToastAlertMessage = new ToastAlertMessage();
	public static CalendarFolder zCalendarFolder = new CalendarFolder();
	public static ListItem zListItem = new ListItem();
	public static MiscObject zMiscObj = new MiscObject();
	public static CalendarGrid zCalendarGrid = new CalendarGrid();
	public static HtmlMenu zHtmlMenu = new HtmlMenu();
}
