<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
<head>

<!-- Generated by ${build.version} on ${build.date} -->
<title>
Zimbra SOAP API Reference ${build.version}
</title>

<LINK REL ="stylesheet" TYPE="text/css" HREF="../stylesheet.css" TITLE="Style">

<script type="text/javascript">
function windowTitle()
{
    parent.document.title="Command ${command.name} (Zimbra SOAP API Reference ${build.version})";
}
</script>

</head>

<body BGCOLOR="white" onload="windowTitle();">

<table cellspacing="3" cellpadding="0" border="0" summary="" bgcolor="#eeeeff">
  <tbody>
  <tr valign="top" align="center">
  <td bgcolor="#ffffff" class="NavBarCell1"> <a href="../overview-summary.html"><font class="NavBarFont1"><b>Overview</b></font></a>&nbsp;</td>
  <td bgcolor="#eeeeff" class="NavBarCell1">    <a href="./service-summary.html"><font class="NavBarFont1"><b>Service</b></font></a>&nbsp;</td>
  <td bgcolor="#eeeeff" class="NavBarCell1Rev">    &nbsp;<font class="NavBarFont1Rev"><b>Command</b></font>&nbsp;</td>
  </tr>
  </tbody>
</table>

<HR>
<H2>
<FONT SIZE="-1"><a href="./service-summary.html">Service ${service.name}</a></FONT>
<BR>
Command ${command.name}</H2>
<p>
!!!
</p>


</body>
</html>
