#!/usr/bin/perl

use strict;

my @objects;

sub clean($) {
    my $line = shift;
    $line =~ s/^\s*//g;
    $line =~ s/\s*$//g;
    return $line. "\n";
}

sub doobject(@) {
    my @lines = @_;
    my %object = ();
    my $lastwhat;
    for (my $i = 0; $i <= $#lines; $i++) {
        my $line = $lines[$i];
        my ($what) = ($line =~ /^(product|vendor|license|text|files|notes):/);
        if (defined($what)) {
            $line =~ s/^(product|vendor|license|text|files|notes)://;
            $object{$what} = clean($line);
            $lastwhat = $what;
        } elsif (defined($lastwhat)) {
            $object{$lastwhat} .= clean($line);
        }
        #print $what, "\n";
    }
    push(@objects, \%object);
}

sub doprint($@) {
    my $type = shift;
    my @sorted = @_;
    open(OUTPUT, "> by$type.html");
    print OUTPUT "<html><title>By $type</title><body><table border=1>\n";
    
    print OUTPUT "<td><b>$type</b></td>\n";

    if ($type ne "license") {
        print OUTPUT "<td><b>License</b></td>\n";
    }
    if ($type ne "product") {
        print OUTPUT "<td><b>Product</b></td>\n";
    }
    if ($type ne "vendor") {
        print OUTPUT "<td><b>Vendor</b></td>\n";
    }
    print OUTPUT "<td><b>Documents</b></td>\n";
    print OUTPUT "<td><b>Notes</b></td>\n";
    print OUTPUT "<td><b>Files</b></td>\n";
    
    foreach my $object (@sorted) {
        print OUTPUT "<tr>\n";
        
        print OUTPUT "<td>", $object->{$type}, "</td>\n";

        if ($type ne "license") {
            if ($object->{license}) {
                print OUTPUT "<td>", $object->{license}, "</td>\n";
            } else {
                print OUTPUT "<td>&nbsp;</td>\n";
            }
        }
        
        
        if ($type ne "product") {
            if ($object->{product}) {
                print OUTPUT "<td>", $object->{product}, "&nbsp;</td>\n";
            } else {
                print OUTPUT "<td>&nbsp;</td>\n";
            }
        }
        
        if ($type ne "vendor") {
            if ($object->{vendor}) {
                print OUTPUT "<td>", $object->{vendor}, "&nbsp;</td>\n";
            } else {
                print OUTPUT "<td>&nbsp;</td>\n";
            }
        }
        
        print OUTPUT "<td>";
        my @licenses = split(/ /, $object->{text});
        foreach my $license (@licenses) {
            $license =~ s/\s*$//g;
            warn "$license: does not exist" unless ($license && -f $license);
            print OUTPUT "<a href='$license'>$license</a><br>\n";
        }
        print OUTPUT "</td>\n";
        
        
        if ($object->{notes}) {
            print OUTPUT "<td>", $object->{notes}, "&nbsp;</td>\n";
        } else {
            print OUTPUT "<td>&nbsp;</td>\n";
        }

        if ($object->{files}) {
            print OUTPUT "<td>", $object->{files}, "&nbsp;</td>\n";
        } else {
            print OUTPUT "<td>&nbsp;</td>\n";
        }

        print OUTPUT "</tr>\n";
    }
    print OUTPUT "</table></body></html>\n";
    close(OUTPUT);
}

my @block = undef;
open(INDEX, "index.txt");
while (<INDEX>) {
    next if /^#/;
    next if /^\s*$/g;
    if (/^-+$/ && defined(@block)) {
        doobject(@block);
        @block = ();
    } else {
        push @block, $_;
    }
}
close(INDEX);

my @bylicense = sort {$a->{license} cmp $b->{license}} @objects;
doprint("license", @bylicense);

my @byvendor = sort {$a->{vendor} cmp $b->{vendor}} @objects;
doprint("vendor", @byvendor);

my @byproduct = sort {$a->{product} cmp $b->{product}} @objects;
doprint("product", @byproduct);
