function FileData_Pairs(x)
{
x.t("dialog","enter");
x.t("administrator","account");
x.t("7071","port");
x.t("credentials","hostname");
x.t("name","administrator");
x.t("name","destination");
x.t("account","destination");
x.t("destination","dialog");
x.t("destination","zimbra");
x.t("destination","server");
x.t("zimbra","server");
x.t("admin","name");
x.t("admin","services");
x.t("admin","port");
x.t("hostname","name");
x.t("enter","zimbra");
x.t("click","next");
x.t("configuration","destination");
x.t("services","run");
x.t("port","7071");
x.t("port","admin");
x.t("port","port");
x.t("run","admin");
x.t("password","administrator");
x.t("password","password");
x.t("server","credentials");
x.t("server","admin");
x.t("server","click");
x.t("server","configuration");
x.t("server","password");
}
